import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { getPublicEntrypointRuntimeRows } from './entrypoint-dag.mjs';

const toolingRoot = path.dirname(fileURLToPath(import.meta.url));

export const repoRoot = path.resolve(toolingRoot, '../..');
export const clientRuntimeProofPath = path.join(
  repoRoot,
  'apps/plite/src/runtime-entrypoint-proof.generated.ts'
);

const quoted = (value) => JSON.stringify(value);

export const createClientRuntimeProofSource = (rows) => {
  const clientRows = (rows ?? getPublicEntrypointRuntimeRows()).filter(
    (row) => row.runtime === 'client'
  );
  const imports = clientRows.map(
    (row, index) =>
      `import * as clientEntrypoint${index} from ${quoted(row.specifier)};`
  );
  const entries = clientRows.map(
    (row, index) =>
      `  { exports: clientEntrypoint${index}, runtimeProof: ${quoted(row.runtimeProof ?? null)}, specifier: ${quoted(row.specifier)} },`
  );

  return [
    '// Generated by pnpm entrypoint:turbo:generate. Do not edit.',
    "'use client';",
    '',
    "import { createEditor as createRuntimeProofEditor, isNominalPluginDescriptor as isRuntimeProofPlugin } from 'platejs/react';",
    ...imports,
    '',
    'const clientRuntimeEntrypoints = [',
    ...entries,
    '] as const;',
    '',
    'export const clientRuntimeEntrypointSpecifiers = clientRuntimeEntrypoints.map(',
    '  ({ specifier }) => specifier',
    ');',
    '',
    'export const exerciseClientRuntimeEntrypoints = () => {',
    "  if (typeof window === 'undefined' || typeof document === 'undefined') {",
    "    throw new Error('Client entrypoint proof requires a browser DOM.');",
    '  }',
    '',
    '  return clientRuntimeEntrypoints.map(({ exports, runtimeProof, specifier }) => {',
    '    const exportCount = Object.keys(exports).length;',
    '',
    '    if (exportCount === 0) {',
    "      throw new Error(specifier + ' has no browser runtime exports.');",
    '    }',
    '',
    "    if (runtimeProof === 'plate-plugin-client') {",
    '      const plugins = Object.values(exports).filter(isRuntimeProofPlugin);',
    '',
    '      if (plugins.length === 0) {',
    "        throw new Error(specifier + ' has no executable Plate plugin descriptor.');",
    '      }',
    '      createRuntimeProofEditor({ plugins, skipInitialization: true });',
    '    }',
    '',
    "    const marker = document.createElement('meta');",
    '    marker.dataset.entrypoint = specifier;',
    '    marker.remove();',
    '',
    '    return { exportCount, specifier };',
    '  });',
    '};',
    '',
  ].join('\n');
};

const ssrProofFactories = {
  'plate-static-html': ({ index, specifier }) => ({
    imports: [
      `import { BaseParagraphPlugin as SsrParagraphPlugin${index}, createEditor as createSsrEditor${index} } from 'platejs';`,
      `import { renderStaticHtml as renderSsrHtml${index} } from ${quoted(specifier)};`,
    ],
    proof: [
      `const ssrHtml${index} = await renderSsrHtml${index}(`,
      `  createSsrEditor${index}({`,
      `    plugins: [SsrParagraphPlugin${index}],`,
      `    initialValue: [{ children: [{ text: 'SSR entrypoint ${index}' }], type: 'paragraph' }],`,
      '  })',
      ');',
      `runtimeEqual(ssrHtml${index}.includes('SSR entrypoint ${index}'), true);`,
    ],
  }),
};

export const createSsrRuntimeProofSource = (rows) => {
  const ssrRows = rows.filter((row) => row.runtime === 'ssr');
  const generated = ssrRows.map((row, index) => {
    const factory = ssrProofFactories[row.runtimeProof];

    if (!factory) {
      throw new Error(
        `${row.specifier} references unknown SSR proof ${String(row.runtimeProof)}.`
      );
    }

    return factory({ index, specifier: row.specifier });
  });

  return [
    "import { equal as runtimeEqual } from 'node:assert/strict';",
    ...generated.flatMap(({ imports }) => imports),
    '',
    "runtimeEqual(typeof globalThis.document, 'undefined');",
    "runtimeEqual(typeof globalThis.window, 'undefined');",
    ...generated.flatMap(({ proof }) => proof),
    '',
  ].join('\n');
};

export const assertClientRuntimeProofGenerated = () => {
  const expected = createClientRuntimeProofSource();
  const actual = fs.existsSync(clientRuntimeProofPath)
    ? fs.readFileSync(clientRuntimeProofPath, 'utf-8')
    : null;

  if (actual !== expected) {
    throw new Error(
      'Client runtime entrypoint proof is stale. Run pnpm entrypoint:turbo:generate.'
    );
  }
};

export const writeClientRuntimeProofGenerated = () => {
  fs.writeFileSync(clientRuntimeProofPath, createClientRuntimeProofSource());
};
