export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './selectOnBackspacePlugin';
`;

export const indexFile = {
  '/select-on-backspace/index.ts': indexCode,
};
