# Generated by Django 3.1.4 on 2021-02-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0009_document_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessright",
            name="path",
            field=models.TextField(blank=True, default=""),
        ),
    ]
