compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableImmutableInstalls: false

nmMode: classic

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.12.0.cjs
