import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createStyleMap, transformStyle } from 'shadcn/utils';

import {
  PLATE_REGISTRY_STYLE_NAMES,
  type PlateRegistryStyleName,
} from '@/lib/plate-registry-styles';

export type RegistryStyleMaps = Record<
  PlateRegistryStyleName,
  Record<string, string>
>;

export function createPreviewStyleCss(styleMaps: RegistryStyleMaps) {
  const styles = PLATE_REGISTRY_STYLE_NAMES.map((style) =>
    Object.entries(styleMaps[style])
      .map(
        ([marker, classes]) =>
          `:where(.style-${style}) :where(.${marker}) {\n  @apply ${classes};\n}`
      )
      .join('\n\n')
  ).join('\n\n');

  return `/* Generated by scripts/sync-shadcn-registry-styles.mts. */\n@layer components {\n${styles.replaceAll(/^/gm, '  ')}\n}\n`;
}

export const SHADCN_STYLE_SOURCE_COMMIT =
  'ee628d75dea87325735fafa7c54f5d7d7edb8774';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
export const REGISTRY_STYLE_ROOT = path.resolve(
  scriptDir,
  '../src/registry/styles'
);

export function findRegistryStyleMarkers(source: string) {
  return [...source.matchAll(/\bcn-[\w-]+\b/g)].map((match) => match[0]);
}

export function getCommonRegistryStyleMarkers(styleMaps: RegistryStyleMaps) {
  const [firstStyle, ...remainingStyles] = PLATE_REGISTRY_STYLE_NAMES;
  const common = new Set(Object.keys(styleMaps[firstStyle]));

  for (const style of remainingStyles) {
    for (const marker of common) {
      if (!(marker in styleMaps[style])) common.delete(marker);
    }
  }

  return common;
}

export async function loadRegistryStyleMaps(
  styleRoot = REGISTRY_STYLE_ROOT
): Promise<RegistryStyleMaps> {
  const provenance = JSON.parse(
    await fs.readFile(path.join(styleRoot, 'provenance.json'), 'utf-8')
  ) as { files: Record<string, string> };
  const entries = await Promise.all(
    PLATE_REGISTRY_STYLE_NAMES.map(async (style) => {
      const fileName = `style-${style}.css`;
      const css = await fs.readFile(path.join(styleRoot, fileName), 'utf-8');
      const hash = createHash('sha256').update(css).digest('hex');

      if (provenance.files[fileName] !== hash) {
        throw new Error(`Vendored shadcn style hash mismatch: ${fileName}`);
      }

      return [style, createStyleMap(css)] as const;
    })
  );

  return Object.fromEntries(entries) as RegistryStyleMaps;
}

export async function transformRegistryStyleSource({
  commonMarkers,
  source,
  styleMap,
}: {
  commonMarkers: ReadonlySet<string>;
  source: string;
  styleMap: Record<string, string>;
}) {
  const markers = findRegistryStyleMarkers(source);

  if (markers.length === 0) return source;

  const unknownMarkers = [...new Set(markers)].filter(
    (marker) => !commonMarkers.has(marker)
  );

  if (unknownMarkers.length > 0) {
    throw new Error(
      `Unknown or incomplete shadcn style markers: ${unknownMarkers.join(', ')}`
    );
  }

  let transformed = source;

  // Upstream de-duplicates a marker within one pass. Re-running the public
  // transformer preserves legitimate repeated static marker placements.
  for (const _marker of markers) {
    const next = await transformStyle(transformed, { styleMap });
    const remainingMarkers = [...new Set(findRegistryStyleMarkers(next))];

    if (remainingMarkers.length === 0) return next;
    if (next === transformed) {
      throw new Error(
        `Unreachable shadcn style markers: ${remainingMarkers.join(', ')}`
      );
    }

    transformed = next;
  }

  throw new Error(
    `Unreachable shadcn style markers: ${[
      ...new Set(findRegistryStyleMarkers(transformed)),
    ].join(', ')}`
  );
}
