import path from 'node:path';

import type { Registry, RegistryItem } from 'shadcn/schema';

const BASE_URL = 'src/';
const PREVIEW_TYPES = new Set<RegistryItem['type']>([
  'registry:block',
  'registry:example',
]);

export function getRegistryIndexComponentPath(item: RegistryItem) {
  if (item.meta?.rsc || !PREVIEW_TYPES.has(item.type)) return null;

  const file = item.files?.[0];

  if (!file) return null;

  return `@/registry/${typeof file === 'string' ? file : file.path}`;
}

export function createRegistryIndexSource(registry: Registry) {
  let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;

  for (const item of registry.items) {
    if (!item.files) continue;

    const componentPath = getRegistryIndexComponentPath(item);

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files.map((file) => {
      const filePath = `${BASE_URL}registry/${typeof file === 'string' ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);

      return typeof file === 'string'
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ''}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : 'null'
    },
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  return `${index}
  }`;
}
