import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

import { createStyleMap } from 'shadcn/utils';

import { PLATE_REGISTRY_STYLE_NAMES } from '@/lib/plate-registry-styles';

import {
  createPreviewStyleCss,
  type RegistryStyleMaps,
  SHADCN_STYLE_SOURCE_COMMIT,
} from './registry-style-transform.mts';

const execFileAsync = promisify(execFile);

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const upstreamRoot = path.resolve(scriptDir, '../../../../shadcn');
const targetRoot = path.resolve(scriptDir, '../src/registry/styles');

async function writeIfChanged(target: string, content: string) {
  const current = await fs.readFile(target, 'utf-8').catch(() => null);

  if (current !== content) {
    await fs.writeFile(target, content);
  }
}

const { stdout } = await execFileAsync('git', [
  '-C',
  upstreamRoot,
  'rev-parse',
  'HEAD',
]);
const upstreamCommit = stdout.trim();

if (upstreamCommit !== SHADCN_STYLE_SOURCE_COMMIT) {
  throw new Error(
    `Expected shadcn ${SHADCN_STYLE_SOURCE_COMMIT}, received ${upstreamCommit}`
  );
}

await fs.mkdir(targetRoot, { recursive: true });

const files: Record<string, string> = {};
const previewMarkers = [
  'cn-command',
  'cn-command-empty',
  'cn-command-group',
  'cn-command-item',
  'cn-command-list',
  'cn-popover-content',
  'cn-popover-content-logical',
  'cn-toggle',
  'cn-toggle-size-default',
  'cn-toggle-size-lg',
  'cn-toggle-size-sm',
  'cn-toggle-variant-default',
  'cn-toggle-variant-outline',
  'cn-tooltip-content',
  'cn-tooltip-content-logical',
] as const;
const previewStyles = Object.fromEntries(
  PLATE_REGISTRY_STYLE_NAMES.map((style) => [style, {}])
) as RegistryStyleMaps;

for (const style of PLATE_REGISTRY_STYLE_NAMES) {
  const fileName = `style-${style}.css`;
  const source = await fs.readFile(
    path.join(upstreamRoot, 'apps/v4/registry/styles', fileName),
    'utf-8'
  );

  files[fileName] = createHash('sha256').update(source).digest('hex');
  const styleMap = createStyleMap(source);
  previewStyles[style] = Object.fromEntries(
    previewMarkers.map((marker) => {
      const classes = styleMap[marker];

      if (!classes) {
        throw new Error(
          `Missing preview style marker ${marker} in ${fileName}`
        );
      }

      return [marker, classes];
    })
  );
  await writeIfChanged(path.join(targetRoot, fileName), source);
}

await writeIfChanged(
  path.join(targetRoot, 'preview-style-classes.ts'),
  `// Generated by scripts/sync-shadcn-registry-styles.mts.\nexport const PLATE_PREVIEW_STYLE_CLASSES = ${JSON.stringify(
    previewStyles,
    null,
    2
  )} as const;\n`
);

await writeIfChanged(
  path.join(targetRoot, 'preview-style-classes.css'),
  createPreviewStyleCss(previewStyles)
);

await writeIfChanged(
  path.join(targetRoot, 'provenance.json'),
  `${JSON.stringify(
    {
      commit: SHADCN_STYLE_SOURCE_COMMIT,
      files,
      source: 'shadcn-ui/ui/apps/v4/registry/styles',
    },
    null,
    2
  )}\n`
);

console.info(
  `Synced ${PLATE_REGISTRY_STYLE_NAMES.length} shadcn registry styles from ${SHADCN_STYLE_SOURCE_COMMIT}`
);
