import { AutoformatRule, ELEMENT_DEFAULT } from '@udecode/plate';
import { formatText } from '../../autoformatUtils';

export const autoformatMathSuperscriptNumbers: AutoformatRule[] = [
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '0',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁰'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '1',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '¹'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '2',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '²'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '3',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '³'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '4',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁴'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '5',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁵'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '6',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁶'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '7',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁷'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '8',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁸'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '9',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁹'),
  },
];

export const autoformatMathSuperscriptSymbols: AutoformatRule[] = [
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: 'o',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '°'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '+',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁺'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '-',
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁻'),
  },
];
