export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './BasicMarkToolbarButtons';
export * from './basicMarkPlugins';
export * from './basicMarksValue';
`;

export const indexFile = {
  '/basic-marks/index.ts': indexCode,
};
