export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './MarkBallonToolbar';
export * from './balloonToolbarValue';
`;

export const indexFile = {
  '/balloon-toolbar/index.ts': indexCode,
};
