const EXPLICIT_CUT_FIXTURES = [
  'transforms/delete/selection/block-inline-over.tsx',
  'transforms/delete/selection/inline-over.tsx',
  'transforms/delete/voids-false/inline-after-reverse.tsx',
  'transforms/delete/voids-false/inline-before.tsx',
  'transforms/delete/voids-false/inline-start.tsx',
  'transforms/delete/voids-false/read-only-inline-after-reverse.tsx',
  'transforms/delete/voids-true/across-blocks.tsx',
  'transforms/general/invalid-insert_node.tsx',
  'transforms/insertFragment/of-blocks/block-end.tsx',
  'transforms/insertFragment/of-blocks/block-middle-3.tsx',
  'transforms/insertFragment/of-blocks/block-nested.tsx',
  'transforms/insertFragment/of-blocks/block-start.tsx',
  'transforms/insertFragment/of-blocks/blocks-middle-1.tsx',
  'transforms/insertFragment/of-blocks/blocks-middle-2.tsx',
  'transforms/insertFragment/of-blocks/with-inline.tsx',
  'transforms/insertFragment/of-inlines/with-text.tsx',
  'transforms/insertFragment/of-lists/merge-lists.tsx',
  'transforms/insertFragment/of-mixed/block-empty.tsx',
  'transforms/insertFragment/of-mixed/block-empty2.tsx',
  'transforms/insertFragment/of-mixed/block-empty3.tsx',
  'transforms/insertFragment/of-mixed/block-end.tsx',
  'transforms/insertFragment/of-mixed/block-end2.tsx',
  'transforms/insertFragment/of-mixed/block-middle.tsx',
  'transforms/insertFragment/of-mixed/block-start.tsx',
  'transforms/insertFragment/of-mixed/block-start2.tsx',
  'transforms/insertFragment/of-texts/block-across.tsx',
  'transforms/insertFragment/of-texts/block-empty.tsx',
  'transforms/insertFragment/of-texts/block-end.tsx',
  'transforms/insertFragment/of-texts/block-middle.tsx',
  'transforms/insertFragment/of-texts/block-start.tsx',
  'transforms/insertFragment/of-texts/inline-empty.tsx',
  'transforms/insertFragment/of-texts/with-multiple.tsx',
  'transforms/insertFragment/voids-true/block.tsx',
  'transforms/insertNodes/block/inline-void.tsx',
  'transforms/insertNodes/path/multiple-inline-not-end.tsx',
  'transforms/insertNodes/path/text.tsx',
  'transforms/insertNodes/voids-true/block.tsx',
  'transforms/insertNodes/voids-true/inline.tsx',
  'transforms/mergeNodes/depth-block/block-nested-multi-child.tsx',
  'transforms/mergeNodes/depth-block/block-nested-only-child.tsx',
  'transforms/mergeNodes/depth-block/block.tsx',
  'transforms/mergeNodes/path/block.tsx',
  'transforms/moveNodes/path/text-nodes.tsx',
  'transforms/moveNodes/path/text.tsx',
  'transforms/moveNodes/voids-true/block.tsx',
  'transforms/moveNodes/voids-true/inline.tsx',
  'transforms/normalization/move_node.tsx',
  'transforms/normalization/split_node-and-insert_node.tsx',
  'transforms/removeNodes/path/inline.tsx',
  'transforms/setNodes/text/merge-across.tsx',
  'transforms/splitNodes/point/inline-void.tsx',
  'transforms/splitNodes/selection/inline-void-end.tsx',
  'transforms/splitNodes/selection/inline-void.tsx',
  'transforms/wrapNodes/split-block/block-mark.tsx',
  'transforms/wrapNodes/split-inline/inline-mark.tsx',
] as const;

const EXPLICIT_CUT_FIXTURE_SET = new Set<string>(EXPLICIT_CUT_FIXTURES);

export const IMPLICIT_CANONICALIZATION_CUT_REASON =
  'Legacy ordinary-op adjacent-text/spacer canonicalization row. The live slate claim keeps this cleanup explicit-only.';

export const isExplicitCutFixture = (fixturePathFromTestRoot: string) =>
  EXPLICIT_CUT_FIXTURE_SET.has(fixturePathFromTestRoot);
