import { AutoformatRule, ELEMENT_DEFAULT } from '@udecode/plate';
import { formatText } from './_utils';

export const mathSuperscriptNumbers: AutoformatRule[] = [
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '0',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁰'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '1',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '¹'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '2',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '²'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '3',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '³'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '4',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁴'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '5',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁵'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '6',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁶'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '7',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁷'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '8',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁸'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '9',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁹'),
  },
];

export const mathSuperscriptSymbols: AutoformatRule[] = [
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: 'o',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '°'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '+',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁺'),
  },
  {
    type: ELEMENT_DEFAULT,
    mode: 'block',
    markup: '^',
    trigger: '-',
    insertTrigger: false,
    triggerAtBlockStart: false,
    format: (editor) => formatText(editor, '⁻'),
  },
];
