import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';

const publicPackageNames = [
  '@platejs/plite',
  '@platejs/yjs',
  '@platejs/browser',
  '@platejs/plite-dom',
  '@platejs/plite-history',
  '@platejs/plite-hyperscript',
  '@platejs/plite-layout',
  '@platejs/plite-react',
];

const publicPackageDirectories: Record<string, string> = {
  '@platejs/browser': 'browser',
  '@platejs/plite': 'plite',
  '@platejs/plite-dom': 'plite-dom',
  '@platejs/plite-history': 'plite-history',
  '@platejs/plite-hyperscript': 'plite-hyperscript',
  '@platejs/plite-layout': 'plite-layout',
  '@platejs/plite-react': 'plite-react',
  '@platejs/yjs': 'yjs',
};

const readPackageJson = (packageName: string) =>
  JSON.parse(
    readFileSync(
      new URL(
        `../../${publicPackageDirectories[packageName]}/package.json`,
        import.meta.url
      ),
      'utf8'
    )
  ) as { exports?: Record<string, unknown> };

const getRuntimeSpecifierFromExportPath = (
  packageName: string,
  exportPath: string
) => {
  if (exportPath === '.') return packageName;

  return `${packageName}/${exportPath.replace(/^\.\//, '')}`;
};

const exactPublicPackageRuntimeExportExpectations = {
  '@platejs/plite': [
    'ChangeSet',
    'DocumentChange',
    'EditorSchemaValidationError',
    'ElementApi',
    'LocationApi',
    'NodeApi',
    'PathApi',
    'PointApi',
    'RangeApi',
    'SelectionApi',
    'SpanApi',
    'TextApi',
    'above',
    'after',
    'before',
    'ContentSlice',
    'createEditor',
    'createEditorRuntime',
    'createEditorView',
    'decodeEditorEffect',
    'defineCommand',
    'defineEditorSchema',
    'defineEffect',
    'defineEditorExtension',
    'defineFacet',
    'defineExtensionSlot',
    'definePropertyPolicy',
    'defineStateField',
    'defineUpdateAnnotation',
    'defineValueCodec',
    'edges',
    'editorCommands',
    'encodeEditorEffect',
    'first',
    'fragment',
    'isBlock',
    'isEdge',
    'isEditor',
    'isEmpty',
    'isEnd',
    'isInline',
    'isSelectable',
    'isStart',
    'isVoid',
    'invertEffect',
    'last',
    'mapEffect',
    'next',
    'parent',
    'previous',
    'property',
    'range',
    'schema',
    'screenReaderAnnouncementEffect',
    'setEditorReadOnly',
    'setDebugValueScrubber',
    'string',
    'target',
    'txOnly',
    'unhangRange',
    'valueCodecs',
  ],
  '@platejs/yjs': [
    'BaseYjsPlugin',
    'YjsUpdatePolicy',
    'createYjsAwarenessSelection',
    'createYjsExtension',
    'readYjsAwarenessSelection',
    'plitePointToYjsRelativePosition',
    'pliteRangeToYjsRelativeRange',
    'yjsAwarenessSelectionsEqual',
    'yjsRelativePositionToPlitePoint',
    'yjsRelativeRangeToPliteRange',
    'yjsRelativeRangesEqual',
  ],
  '@platejs/yjs/core': [
    'YjsUpdatePolicy',
    'createYjsAwarenessSelection',
    'createYjsExtension',
    'readYjsAwarenessSelection',
    'plitePointToYjsRelativePosition',
    'pliteRangeToYjsRelativeRange',
    'yjsAwarenessSelectionsEqual',
    'yjsRelativePositionToPlitePoint',
    'yjsRelativeRangeToPliteRange',
    'yjsRelativeRangesEqual',
  ],
  '@platejs/yjs/react': [
    'YjsPlugin',
    'getYjsAwarenessRevision',
    'getYjsProviderRevision',
    'getYjsProviderStatus',
    'getYjsProviderSynced',
    'useYjsAwarenessRevision',
    'useYjsProviderRevision',
    'useYjsProviderStatus',
    'useYjsProviderSynced',
    'useYjsRemoteCursor',
    'useYjsRemoteCursorDecorationSource',
    'useYjsRemoteCursorOverlayPositions',
    'useYjsRemoteCursors',
  ],
  '@platejs/browser/browser': [
    'inspectZeroWidthPlaceholder',
    'takeDOMSelectionSnapshot',
    'takeEditorSelectionSnapshot',
  ],
  '@platejs/browser/core': [
    'PLITE_BROWSER_FIRST_PARTY_FEATURE_CONTRACT_REGISTRY',
    'PLITE_BROWSER_FIRST_PARTY_INTENT_FAMILY_CONTRACTS',
    'PLITE_BROWSER_FIRST_PARTY_PARITY_FAMILIES',
    'PLITE_BROWSER_RELEASE_DISCIPLINE_GUARDS',
    'assertPliteBrowserFirstPartyParityContracts',
    'assertPliteBrowserReleaseProof',
    'classifyBrowserMobileTransportProof',
    'createBrowserMobileReleaseProofArtifact',
    'createPersistentBrowserSoakProofArtifact',
    'createReleaseDisciplineProofArtifact',
    'createPliteBrowserFeatureContractRegistry',
    'definePliteBrowserFeatureContract',
    'evaluateImeInput',
    'evaluatePlaceholderInput',
    'extractAgentBrowserDebugSnapshot',
    'extractAppiumDebugSnapshot',
    'getBrowserMobileTransportProofMatrix',
    'isCollapsed',
    'parseAgentBrowserBatch',
    'parseDebugSnapshot',
    'serializePoint',
    'serializeRange',
    'validatePliteBrowserReleaseProof',
  ],
  '@platejs/browser/playwright': [
    'assertNoIllegalKernelTransitions',
    'assertPliteBrowserCaretVisibleInScrollableParent',
    'assertPliteBrowserKernelTraceEntry',
    'assertPliteBrowserSelectionContract',
    'attachPageScreenshot',
    'attachPliteBrowserJsonArtifact',
    'attachPliteBrowserSelectionScreenshot',
    'browserStep',
    'classifyScenarioTransportClaim',
    'createScenarioReductionCandidates',
    'createScenarioReplay',
    'createPliteBrowserClipboardPasteGauntlet',
    'createPliteBrowserCompositionGauntlet',
    'createPliteBrowserDestructiveEditingGauntlet',
    'createPliteBrowserDropDataGauntlet',
    'createPliteBrowserEditorHarness',
    'createPliteBrowserFeatureContractRegistry',
    'createPliteBrowserInlineCutTypingGauntlet',
    'createPliteBrowserInternalControlGauntlet',
    'createPliteBrowserMarkClickTypingGauntlet',
    'createPliteBrowserMarkTypingGauntlet',
    'createPliteBrowserMixedEditingConformanceGauntlet',
    'createPliteBrowserNavigationTypingGauntlet',
    'createPliteBrowserSemanticEditingConformanceGauntlet',
    'createPliteBrowserShellActivationGauntlet',
    'createPliteBrowserTextInsertionGauntlet',
    'createPliteBrowserToolbarMarkClickTypingGauntlet',
    'createPliteBrowserWarmLoopSteps',
    'createPliteBrowserWarmToolbarArrowGauntlet',
    'decodeScenarioReplay',
    'definePliteBrowserFeatureContract',
    'findPliteBrowserKernelTraceEntry',
    'getIllegalKernelTransitions',
    'getPliteBrowserEditable',
    'getPliteReactRenderProfilerSnapshot',
    'installPliteReactRenderProfiler',
    'locatePliteBrowserBlock',
    'locatePliteBrowserText',
    'matchesPliteBrowserKernelTrace',
    'normalizeScenarioMetadata',
    'openExample',
    'openExampleWithOptions',
    'recordPliteBrowserRuntimeErrors',
    'resetPliteBrowserNativeEventTrace',
    'resetPliteReactRenderProfiler',
    'serializeScenarioStepForReplay',
    'startPliteBrowserNativeEventTrace',
    'stopPliteBrowserNativeEventTrace',
    'summarizeScenarioReductionCandidate',
    'summarizeScenarioStep',
    'takeDOMSelectionSnapshot',
    'takeDisplayedSelectionSnapshotForRoot',
    'takeSelectionSnapshot',
    'takePliteBrowserNativeEventTrace',
    'takePliteBrowserRenderStateSnapshot',
    'withExclusiveClipboardAccess',
  ],
  '@platejs/plite-dom': [
    'CAN_USE_DOM',
    'DOMCoverage',
    'HAS_BEFORE_INPUT_SUPPORT',
    'Hotkeys',
    'IS_ANDROID',
    'IS_CHROME',
    'IS_FIREFOX',
    'IS_IOS',
    'IS_UC_MOBILE',
    'IS_WEBKIT',
    'IS_WECHATBROWSER',
    'Key',
    'PliteDOMResolutionError',
    'TRIPLE_CLICK',
    'applyStringDiff',
    'closestShadowAware',
    'containsShadowAware',
    'defineHostCodec',
    'dom',
    'getActiveElement',
    'getDOMClipboardFormatKey',
    'getDefaultView',
    'getElements',
    'getNodeDataAttributeKeys',
    'getSelection',
    'hasShadowRoot',
    'hostCodecs',
    'isAfter',
    'isApplePlatform',
    'isBefore',
    'isDOMElement',
    'isDOMNode',
    'isDOMSelection',
    'isDOMText',
    'isEditor',
    'isElement',
    'isElementDecorationsEqual',
    'isHotkey',
    'isLeaf',
    'isNode',
    'isPlainTextOnlyPaste',
    'isString',
    'isText',
    'isTextDecorationsEqual',
    'isTrackedMutation',
    'isVoid',
    'keyToDataAttribute',
    'mergeStringDiffs',
    'normalizeDOMPoint',
    'normalizePoint',
    'normalizeRange',
    'normalizeStringDiff',
    'parseDOMClipboardHtml',
    'splitDecorationsByChild',
    'targetRange',
    'verifyDiffState',
    'writeDOMFragmentData',
    'writeDOMRangeData',
    'writeHostFragmentData',
  ],
  '@platejs/plite-history': ['History', 'history'],
  '@platejs/plite-hyperscript': [
    'createEditor',
    'createEditorFixture',
    'createHyperscript',
    'createText',
    'jsx',
  ],
  '@platejs/plite-layout': [
    'createEstimatedPageLayoutEngine',
    'createPliteLayout',
    'createPlitePage',
    'createPlitePageBreakSnapshot',
    'createPlitePageLayout',
    'getPlitePageLayoutDecorations',
    'getPlitePageLayoutFragments',
    'getPlitePageLayoutGeometry',
    'getPlitePageLayoutPathKey',
    'getPlitePageLayoutProjection',
    'getPlitePagePresetSize',
    'normalizePlitePageSettings',
    'paginatePlitePageLayoutBlocks',
    'plitePageBreakSnapshotCodec',
    'plitePageSettingsCodec',
    'pretextPageLayoutEngine',
  ],
  '@platejs/plite-layout/react': [
    'PagedEditable',
    'usePliteLayout',
    'usePliteLayoutFragments',
    'usePliteLayoutFragmentsAtPath',
    'usePliteLayoutSnapshot',
    'usePlitePageLayout',
    'usePlitePageLayoutSnapshot',
  ],
  '@platejs/plite-react': [
    'Editable',
    'EditableElement',
    'EditorReadOnlyProvider',
    'Plite',
    'PliteElement',
    'PliteLeaf',
    'PlitePlaceholder',
    'PliteReactUpdatePolicy',
    'PliteRuntime',
    'PliteText',
    'createReactEditor',
    'defaultScrollSelectionIntoView',
    'react',
    'useDOMStrategyVirtualOffset',
    'useDecorationSelector',
    'useEditor',
    'useEditorComposing',
    'useEditorEditableElement',
    'useEditorFocused',
    'useEditorReadOnly',
    'useEditorRootElement',
    'useEditorRuntimeState',
    'useEditorScrollElement',
    'useEditorScrollElementRef',
    'useEditorSelection',
    'useEditorSelector',
    'useEditorState',
    'useEditorViewState',
    'useElement',
    'useElementPath',
    'useElementSelected',
    'useNodeSelector',
    'useOptionalEditorReadOnly',
    'useOptionalElement',
    'useSetStateField',
    'usePliteActiveEditor',
    'usePliteActiveRoot',
    'usePliteAnnotation',
    'usePliteAnnotationStore',
    'usePliteAnnotations',
    'usePliteChildRoot',
    'usePliteCommand',
    'usePliteContentRoot',
    'usePliteDecorationSource',
    'usePliteEditor',
    'usePliteHistory',
    'usePliteNodeRef',
    'usePliteProjectionEntries',
    'usePliteRangeDecorationSource',
    'usePliteRootChrome',
    'usePliteRootEditor',
    'usePliteRootEffect',
    'usePliteRootState',
    'usePliteRuntime',
    'usePliteRuntimeState',
    'usePliteWidget',
    'usePliteWidgetStore',
    'usePliteWidgets',
    'useStateFieldValue',
    'useTextSelector',
  ],
};

const internalBridgeRuntimeExportExpectations = {
  '@platejs/plite/internal': [
    'EditorSchemaCompileError',
    'IndexedDocument',
    'MAIN_ROOT_KEY',
    'above',
    'addMark',
    'after',
    'applyBuiltDocumentChange',
    'areEditorJsonValuesEqual',
    'areEditorSchemaIdentitiesEqual',
    'assertEditorJsonValue',
    'assertPublicRootKey',
    'assertSelectionSupported',
    'before',
    'collapse',
    'compileEditorSchemaContributions',
    'createEditorEffect',
    'createDetachedContentSlice',
    'createInternalClipboardApi',
    'createInternalDocumentChange',
    'decodeEditorEffect',
    'decodeEditorSelection',
    'decodeVersionedValue',
    'defineCommand',
    'defineEditorExtension',
    'delete',
    'deleteBackward',
    'deleteForward',
    'deleteFragment',
    'deselect',
    'dispatchCommand',
    'edges',
    'editorCommands',
    'elementReadOnly',
    'encodeEditorEffect',
    'encodeEditorSelection',
    'encodeVersionedValue',
    'extend',
    'failInvariant',
    'first',
    'formatDebugValue',
    'fragment',
    'getActiveEditorTransaction',
    'getChildren',
    'getCollabEffectTypes',
    'getCollabEffects',
    'getCompiledEditorConfiguration',
    'getCompiledEditorSchema',
    'getCompiledEditorSchemaFromApi',
    'getCompiledPropertyMergeStrategy',
    'getCompiledSchemaPropertyId',
    'getDocumentChangeRelocations',
    'getExactDocumentChangeRelocations',
    'getEditorCommitSnapshot',
    'getEditorCurrentMarks',
    'getEditorDefaultBlockType',
    'getEditorExtensionRegistry',
    'getEditorLiveNode',
    'getEditorLiveSelection',
    'getEditorLiveText',
    'getEditorMaxLength',
    'getEditorRuntime',
    'getEditorRuntimeElementEntries',
    'getEditorRuntimeIdForNode',
    'getEditorRuntimeOwner',
    'getEditorRuntimeRootKeys',
    'getEditorSelectionRoot',
    'getEditorStateView',
    'getEditorUpdateRoot',
    'getExtensionRegistry',
    'getFragment',
    'getInstalledEditorExtension',
    'getInternalDocumentChangeClassification',
    'getInternalDocumentChangeClassificationEntries',
    'getInternalDocumentChangeEntries',
    'getInternalDocumentChangeSet',
    'getLastCommit',
    'getPathByRuntimeId',
    'getRangeRoot',
    'getRuntimeId',
    'getSelection',
    'getSnapshot',
    'getSnapshotVersion',
    'getStateFieldEffectTypes',
    'hasBlocks',
    'hasCommandHandler',
    'hasEditorRuntime',
    'hasInlines',
    'hasPath',
    'hasTexts',
    'inheritEditorExtensionRegistry',
    'initializeEditorExtensions',
    'insertBreak',
    'insertNode',
    'insertNodes',
    'insertSoftBreak',
    'insertText',
    'isBlock',
    'isEdge',
    'isEditor',
    'isPropertyPolicyToken',
    'isElementReadOnly',
    'isEmpty',
    'isEnd',
    'isInline',
    'isObject',
    'isSelectable',
    'isStart',
    'isVoid',
    'last',
    'leaf',
    'levels',
    'liftNodes',
    'mapInternalDocumentChangePosition',
    'mapSelectionThroughChange',
    'matchesCompiledSchemaTarget',
    'mergeNodes',
    'move',
    'moveNodes',
    'next',
    'parent',
    'path',
    'point',
    'positions',
    'previous',
    'projectRange',
    'projectRangeInSnapshot',
    'range',
    'read',
    'readEditorSchemaIdentity',
    'removeMark',
    'removeNodes',
    'replaceChildren',
    'replace',
    'reset',
    'reportEditorLifecycleError',
    'resolveCompiledSchemaProperty',
    'runTrustedUpdate',
    'scheduleAfterCommitNotification',
    'select',
    'setEditorChildren',
    'setEditorComposing',
    'setEditorDefaultBlockType',
    'setEditorFocused',
    'setEditorMarks',
    'setEditorMaxLength',
    'setEditorReadOnly',
    'setEditorRuntime',
    'setEditorSelection',
    'setEditorTargetRuntime',
    'setNodes',
    'setPoint',
    'setSelection',
    'shouldMergeNodesRemovePrevNode',
    'splitNodes',
    'string',
    'subscribe',
    'subscribeCommit',
    'subscribeEditorViewState',
    'subscribeSource',
    'toEditorCoreStateView',
    'toInternalRoot',
    'toPublicRoot',
    'toggleBlock',
    'toggleMark',
    'unhangRange',
    'unsetNodes',
    'update',
    'unwrapNodes',
    'void',
    'withEditorUpdateRootScope',
    'wrapNodes',
  ],
  '@platejs/plite-dom/internal': [
    'DOMCoverage',
    'DOMEditor',
    'EDITOR_TO_DOM_EDITABLE',
    'EDITOR_TO_DOM_ROOT',
    'EDITOR_TO_DOM_SCOPE_LISTENERS',
    'EDITOR_TO_DOM_SCROLL',
    'EDITOR_TO_ELEMENT',
    'EDITOR_TO_FORCE_RENDER',
    'EDITOR_TO_KEY_TO_ELEMENT',
    'EDITOR_TO_PENDING_ACTION',
    'EDITOR_TO_PENDING_DIFFS',
    'EDITOR_TO_PENDING_INSERTION_MARKS',
    'EDITOR_TO_PENDING_SELECTION',
    'EDITOR_TO_PLACEHOLDER_ELEMENT',
    'EDITOR_TO_ROOT_VIEW_EDITORS',
    'EDITOR_TO_SCHEDULE_FLUSH',
    'EDITOR_TO_USER_MARKS',
    'EDITOR_TO_USER_SELECTION',
    'EDITOR_TO_WINDOW',
    'ELEMENT_TO_NODE',
    'IS_COMPOSING',
    'IS_FOCUSED',
    'IS_NODE_MAP_DIRTY',
    'IS_READ_ONLY',
    'MARK_PLACEHOLDER_SYMBOL',
    'NODE_TO_ELEMENT',
    'NODE_TO_INDEX',
    'NODE_TO_KEY',
    'NODE_TO_PARENT',
    'NODE_TO_RUNTIME_ID',
    'PLACEHOLDER_SYMBOL',
    'createDOMEditorCapability',
    'createDOMGeometryKernel',
    'createDOMPhaseScheduler',
    'destroyEditorDOMPhaseSchedulerFallback',
    'getDOMClipboardFormatKey',
    'getElements',
    'getNodeDataAttributeKeys',
    'getPliteStringCoordinatePlacement',
    'getPliteStringDocumentOffset',
    'getPliteStringEdgeOffset',
    'getPliteStringLength',
    'getPliteStringLineEdgeTextOffset',
    'getPliteStringPlacementDOMPoint',
    'hasUsableDOMRect',
    'isEditor',
    'isElement',
    'isLeaf',
    'isNode',
    'isString',
    'isText',
    'isVoid',
    'installEditorDOMPhaseScheduler',
    'keyToDataAttribute',
    'parseDOMClipboardHtml',
    'readDOMFragmentData',
    'scheduleEditorDOMPhase',
    'setDOMClipboardFormatKey',
    'setEditorDOMEditableElement',
    'setEditorDOMRootElement',
    'setEditorDOMScrollElement',
    'subscribeEditorDOMScope',
    'writeDOMHostFragmentData',
  ],
};

describe('public package imports', () => {
  test('covers every public package export specifier with exact runtime smoke', () => {
    const publicExportSpecifiers = publicPackageNames
      .flatMap((packageName) =>
        Object.keys(readPackageJson(packageName).exports ?? {}).map(
          (exportPath) =>
            getRuntimeSpecifierFromExportPath(packageName, exportPath)
        )
      )
      .filter(
        (specifier) =>
          !specifier.endsWith('/internal') &&
          !specifier.endsWith('/package.json')
      )
      .sort();

    expect(
      Object.keys(exactPublicPackageRuntimeExportExpectations).sort()
    ).toEqual(publicExportSpecifiers);
  });

  for (const [specifier, names] of Object.entries(
    exactPublicPackageRuntimeExportExpectations
  )) {
    test(`keeps ${specifier} runtime exports exact`, async () => {
      const module = await import(specifier);
      const exportedNames = Object.keys(module).sort();

      expect(exportedNames).toEqual([...names].sort());
    });
  }

  for (const [specifier, names] of Object.entries(
    internalBridgeRuntimeExportExpectations
  )) {
    test(`keeps ${specifier} runtime exports exact`, async () => {
      const module = await import(specifier);
      const exportedNames = Object.keys(module).sort();

      expect(exportedNames).toEqual([...names].sort());
    });
  }

  test('keeps plite-browser root unavailable', async () => {
    let importedRoot = false;
    const browserRootSpecifier = '@platejs/browser' as string;

    try {
      await import(browserRootSpecifier);
      importedRoot = true;
    } catch {}

    expect(importedRoot).toBe(false);
  });
});
