export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './IndentToolbarButtons';
export * from './indentPlugin';
export * from './indentValue';
`;

export const indexFile = {
  '/indent/index.ts': indexCode,
};
