/**
 * @file Automatically generated by barrelsby.
 */

export * from './getCellInNextTableRow';
export * from './getCellInPreviousTableRow';
export * from './getColSpan';
export * from './getLeftTableCell';
export * from './getNextTableCell';
export * from './getPreviousTableCell';
export * from './getRowSpan';
export * from './getSelectedCellsBorders';
export * from './getSelectedCellsBoundingBox';
export * from './getTableAbove';
export * from './getTableCellBorders';
export * from './getTableCellSize';
export * from './getTableColumnCount';
export * from './getTableColumnIndex';
export * from './getTableEntries';
export * from './getTableGridAbove';
export * from './getTableGridByRange';
export * from './getTableOverriddenColSizes';
export * from './getTableRowIndex';
export * from './getTopTableCell';
export * from './isTableBorderHidden';
