/* Generated by @platejs/cli from src/registry/components/editor/plugins.ts.
 * Regenerate with: pnpm exec plate generate -- src/registry/components/editor/plugins.ts
 * Do not edit.
 */
import type { Element, GeneratedEditorTypeProvider, Text } from 'platejs';
import type { Editor as BaseEditor } from 'platejs/react';

import type * as EditorModule from "./plugins";

export interface EditorText extends Text {
  readonly text: string;
  readonly ai?: boolean;
  readonly backgroundColor?: string;
  readonly bold?: boolean;
  readonly code?: boolean;
  readonly codeSyntax?: boolean;
  readonly color?: string;
  readonly comment?: boolean;
  readonly commentTransient?: boolean;
  readonly fontFamily?: string;
  readonly fontSize?: string;
  readonly highlight?: boolean;
  readonly italic?: boolean;
  readonly kbd?: boolean;
  readonly script?: "sub" | "sup";
  readonly strikethrough?: boolean;
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
  readonly underline?: boolean;
}

export interface AiChatElement extends Element {
  readonly children: readonly (EditorText)[];
  readonly type: "aiChat";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface AudioElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "audio";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
  readonly url: string;
  readonly width?: number | string;
}

export interface BlockquoteElement extends Element {
  readonly children: readonly (AiChatElement | AudioElement | BlockquoteElement | CalloutElement | CodeBlockElement | ColumnGroupElement | DetailsElement | EquationElement | FileElement | FootnoteDefinitionElement | HeadingElement | HorizontalRuleElement | ImageElement | MediaEmbedElement | ParagraphElement | PlaceholderElement | DetailsSummaryElement | TableElement | TocElement | VideoElement)[];
  readonly type: "blockquote";
  readonly aiPreview?: boolean;
  readonly checked?: boolean;
  readonly indent?: number;
  readonly listRestart?: number;
  readonly listStart?: number;
  readonly listStyle?: string;
  readonly listType?: "bulleted" | "numbered" | "task";
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface CalloutElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "callout";
  readonly aiPreview?: boolean;
  readonly backgroundColor?: string;
  readonly icon: string;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly variant?: string;
}

export interface CodeBlockElement extends Element {
  readonly children: readonly (CodeLineElement)[];
  readonly type: "codeBlock";
  readonly aiPreview?: boolean;
  readonly checked?: boolean;
  readonly indent?: number;
  readonly language?: string;
  readonly listRestart?: number;
  readonly listStart?: number;
  readonly listStyle?: string;
  readonly listType?: "bulleted" | "numbered" | "task";
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface CodeLineElement extends Element {
  readonly children: readonly (EditorText)[];
  readonly type: "codeLine";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface ColumnElement extends Element {
  readonly children: readonly (AiChatElement | AudioElement | BlockquoteElement | CalloutElement | CodeBlockElement | ColumnGroupElement | DetailsElement | EquationElement | FileElement | FootnoteDefinitionElement | HeadingElement | HorizontalRuleElement | ImageElement | MediaEmbedElement | ParagraphElement | PlaceholderElement | DetailsSummaryElement | TableElement | TocElement | VideoElement)[];
  readonly type: "column";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly width: string;
}

export interface ColumnGroupElement extends Element {
  readonly children: readonly (ColumnElement)[];
  readonly type: "columnGroup";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface DateElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "date";
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
  readonly value: string;
}

export interface DetailsElement extends Element {
  readonly children: readonly (AiChatElement | AudioElement | BlockquoteElement | CalloutElement | CodeBlockElement | ColumnGroupElement | DetailsElement | EquationElement | FileElement | FootnoteDefinitionElement | HeadingElement | HorizontalRuleElement | ImageElement | MediaEmbedElement | ParagraphElement | PlaceholderElement | DetailsSummaryElement | TableElement | TocElement | VideoElement)[];
  readonly type: "details";
  readonly aiPreview?: boolean;
  readonly checked?: boolean;
  readonly indent?: number;
  readonly listRestart?: number;
  readonly listStart?: number;
  readonly listStyle?: string;
  readonly listType?: "bulleted" | "numbered" | "task";
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface EmojiInputElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "emojiInput";
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
  readonly trigger?: string;
  readonly userId?: string;
  readonly value?: string;
}

export interface EquationElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "equation";
  readonly aiPreview?: boolean;
  readonly latex: string;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface FileElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "file";
  readonly aiPreview?: boolean;
  readonly name?: string;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly url: string;
  readonly width?: number | string;
}

export interface FootnoteDefinitionElement extends Element {
  readonly children: readonly (AiChatElement | AudioElement | BlockquoteElement | CalloutElement | CodeBlockElement | ColumnGroupElement | DetailsElement | EquationElement | FileElement | FootnoteDefinitionElement | HeadingElement | HorizontalRuleElement | ImageElement | MediaEmbedElement | ParagraphElement | PlaceholderElement | DetailsSummaryElement | TableElement | TocElement | VideoElement)[];
  readonly type: "footnoteDefinition";
  readonly aiPreview?: boolean;
  readonly ref: string;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface FootnoteInputElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "footnoteInput";
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
  readonly trigger?: string;
  readonly userId?: string;
  readonly value?: string;
}

export interface FootnoteElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "footnoteReference";
  readonly ref: string;
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
}

export interface HeadingElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "heading";
  readonly aiPreview?: boolean;
  readonly checked?: boolean;
  readonly indent?: number;
  readonly level: 1 | 2 | 3 | 4 | 5 | 6;
  readonly lineHeight?: number | string;
  readonly listRestart?: number;
  readonly listStart?: number;
  readonly listStyle?: string;
  readonly listType?: "bulleted" | "numbered" | "task";
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
}

export interface HorizontalRuleElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "horizontalRule";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface ImageElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "image";
  readonly aiPreview?: boolean;
  readonly alt?: string;
  readonly checked?: boolean;
  readonly indent?: number;
  readonly listRestart?: number;
  readonly listStart?: number;
  readonly listStyle?: string;
  readonly listType?: "bulleted" | "numbered" | "task";
  readonly naturalHeight?: number;
  readonly naturalWidth?: number;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
  readonly title?: string;
  readonly url: string;
  readonly width?: number | string;
}

export interface InlineEquationElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "inlineEquation";
  readonly latex: string;
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
}

export interface LinkElement extends Element {
  readonly children: readonly (EditorText)[];
  readonly type: "link";
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
  readonly target?: string;
  readonly url: string;
}

export interface MediaEmbedElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "mediaEmbed";
  readonly aiPreview?: boolean;
  readonly provider?: string;
  readonly sourceUrl?: string;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
  readonly url: string;
  readonly width?: number | string;
}

export interface MentionElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "mention";
  readonly label?: string;
  readonly ref: string;
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
}

export interface MentionInputElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "mentionInput";
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
  readonly trigger?: string;
  readonly userId?: string;
  readonly value?: string;
}

export interface ParagraphElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "paragraph";
  readonly aiPreview?: boolean;
  readonly checked?: boolean;
  readonly indent?: number;
  readonly lineHeight?: number | string;
  readonly listRestart?: number;
  readonly listStart?: number;
  readonly listStyle?: string;
  readonly listType?: "bulleted" | "numbered" | "task";
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
}

export interface PlaceholderElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "placeholder";
  readonly aiPreview?: boolean;
  readonly mediaType: string;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface SlashInputElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "slashInput";
  readonly suggestion?: boolean;
  readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
  readonly suggestionTransient?: boolean;
  readonly trigger?: string;
  readonly userId?: string;
  readonly value?: string;
}

export interface DetailsSummaryElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "summary";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface TableElement extends Element {
  readonly children: readonly (TableRowElement)[];
  readonly type: "table";
  readonly aiPreview?: boolean;
  readonly columnWidths?: readonly (null | number)[];
  readonly marginLeft?: number;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface TableCellElement extends Element {
  readonly children: readonly (AiChatElement | AudioElement | BlockquoteElement | CalloutElement | CodeBlockElement | ColumnGroupElement | DetailsElement | EquationElement | FileElement | FootnoteDefinitionElement | HeadingElement | HorizontalRuleElement | ImageElement | MediaEmbedElement | ParagraphElement | PlaceholderElement | DetailsSummaryElement | TableElement | TocElement | VideoElement)[];
  readonly type: "tableCell";
  readonly aiPreview?: boolean;
  readonly backgroundColor?: string;
  readonly borders?: { readonly bottom?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly left?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly right?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly top?: { readonly color?: string; readonly style?: string; readonly width?: number; }; };
  readonly colSpan?: number;
  readonly header?: boolean;
  readonly rowSpan?: number;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface TableRowElement extends Element {
  readonly children: readonly (TableCellElement)[];
  readonly type: "tableRow";
  readonly aiPreview?: boolean;
  readonly height?: number;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface TocElement extends Element {
  readonly children: readonly [EditorText];
  readonly type: "toc";
  readonly aiPreview?: boolean;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
}

export interface VideoElement extends Element {
  readonly children: readonly (DateElement | EmojiInputElement | FootnoteInputElement | FootnoteElement | InlineEquationElement | LinkElement | MentionElement | MentionInputElement | SlashInputElement | EditorText)[];
  readonly type: "video";
  readonly aiPreview?: boolean;
  readonly provider?: string;
  readonly sourceUrl?: string;
  readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
  readonly suggestionTransient?: boolean;
  readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
  readonly url: string;
  readonly width?: number | string;
}

export type EditorElement = AiChatElement | AudioElement | BlockquoteElement | CalloutElement | CodeBlockElement | CodeLineElement | ColumnElement | ColumnGroupElement | DateElement | DetailsElement | EmojiInputElement | EquationElement | FileElement | FootnoteDefinitionElement | FootnoteInputElement | FootnoteElement | HeadingElement | HorizontalRuleElement | ImageElement | InlineEquationElement | LinkElement | MediaEmbedElement | MentionElement | MentionInputElement | ParagraphElement | PlaceholderElement | SlashInputElement | DetailsSummaryElement | TableElement | TableCellElement | TableRowElement | TocElement | VideoElement;
export type Value = readonly (AiChatElement | AudioElement | BlockquoteElement | CalloutElement | CodeBlockElement | ColumnGroupElement | DetailsElement | EquationElement | FileElement | FootnoteDefinitionElement | HeadingElement | HorizontalRuleElement | ImageElement | MediaEmbedElement | ParagraphElement | PlaceholderElement | DetailsSummaryElement | TableElement | TocElement | VideoElement)[];
export type Schema = Readonly<{
  readonly plugins: Readonly<{
    readonly paragraph: Readonly<{ readonly type: "paragraph"; }>;
    readonly ai: Readonly<{ readonly key: "ai"; }>;
    readonly suggestion: Readonly<{ readonly key: "suggestion"; }>;
    readonly aiChat: Readonly<{ readonly type: "aiChat"; }>;
    readonly heading: Readonly<{ readonly type: "heading"; }>;
    readonly blockquote: Readonly<{ readonly type: "blockquote"; }>;
    readonly horizontalRule: Readonly<{ readonly type: "horizontalRule"; }>;
    readonly codeLine: Readonly<{ readonly type: "codeLine"; }>;
    readonly codeBlock: Readonly<{ readonly type: "codeBlock"; }>;
    readonly codeSyntax: Readonly<{ readonly key: "codeSyntax"; }>;
    readonly tableCell: Readonly<{ readonly type: "tableCell"; }>;
    readonly tableRow: Readonly<{ readonly type: "tableRow"; }>;
    readonly table: Readonly<{ readonly type: "table"; }>;
    readonly detailsSummary: Readonly<{ readonly type: "summary"; }>;
    readonly details: Readonly<{ readonly type: "details"; }>;
    readonly toc: Readonly<{ readonly type: "toc"; }>;
    readonly image: Readonly<{ readonly type: "image"; }>;
    readonly mediaEmbed: Readonly<{ readonly type: "mediaEmbed"; }>;
    readonly video: Readonly<{ readonly type: "video"; }>;
    readonly audio: Readonly<{ readonly type: "audio"; }>;
    readonly file: Readonly<{ readonly type: "file"; }>;
    readonly placeholder: Readonly<{ readonly type: "placeholder"; }>;
    readonly callout: Readonly<{ readonly type: "callout"; }>;
    readonly column: Readonly<{ readonly type: "column"; }>;
    readonly columnGroup: Readonly<{ readonly type: "columnGroup"; }>;
    readonly inlineEquation: Readonly<{ readonly type: "inlineEquation"; }>;
    readonly equation: Readonly<{ readonly type: "equation"; }>;
    readonly date: Readonly<{ readonly type: "date"; }>;
    readonly link: Readonly<{ readonly type: "link"; }>;
    readonly mentionInput: Readonly<{ readonly type: "mentionInput"; }>;
    readonly mention: Readonly<{ readonly type: "mention"; }>;
    readonly footnoteInput: Readonly<{ readonly type: "footnoteInput"; }>;
    readonly footnote: Readonly<{ readonly type: "footnoteReference"; }>;
    readonly footnoteDefinition: Readonly<{ readonly type: "footnoteDefinition"; }>;
    readonly bold: Readonly<{ readonly key: "bold"; }>;
    readonly italic: Readonly<{ readonly key: "italic"; }>;
    readonly underline: Readonly<{ readonly key: "underline"; }>;
    readonly code: Readonly<{ readonly key: "code"; }>;
    readonly strikethrough: Readonly<{ readonly key: "strikethrough"; }>;
    readonly script: Readonly<{ readonly key: "script"; }>;
    readonly highlight: Readonly<{ readonly key: "highlight"; }>;
    readonly kbd: Readonly<{ readonly key: "kbd"; }>;
    readonly color: Readonly<{ readonly key: "color"; }>;
    readonly backgroundColor: Readonly<{ readonly key: "backgroundColor"; }>;
    readonly fontSize: Readonly<{ readonly key: "fontSize"; }>;
    readonly fontFamily: Readonly<{ readonly key: "fontFamily"; }>;
    readonly indent: Readonly<{ readonly key: "indent"; }>;
    readonly textAlign: Readonly<{ readonly key: "textAlign"; }>;
    readonly lineHeight: Readonly<{ readonly key: "lineHeight"; }>;
    readonly comment: Readonly<{ readonly key: "comment"; }>;
    readonly slashInput: Readonly<{ readonly type: "slashInput"; }>;
    readonly emojiInput: Readonly<{ readonly type: "emojiInput"; }>;
  }>;
  readonly properties: Readonly<Record<PropertyKey, never>>;
}>;
export type Mutations = Readonly<{
  readonly aiChat: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly toggle: true;
    readonly type: "aiChat";
  }>;
  readonly audio: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly type: "audio";
  }>;
  readonly blockquote: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "blockquote";
  }>;
  readonly callout: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly backgroundColor?: string;
      readonly icon?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly variant?: string;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly backgroundColor?: string;
      readonly icon: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly variant?: string;
    }>;
    readonly toggle: true;
    readonly type: "callout";
  }>;
  readonly codeBlock: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly language?: string;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly language?: string;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "codeBlock";
  }>;
  readonly codeLine: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "codeLine";
  }>;
  readonly column: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly width?: string;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly width: string;
    }>;
    readonly type: "column";
  }>;
  readonly columnGroup: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "columnGroup";
  }>;
  readonly date: Readonly<{
    readonly construction: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly value: string;
    }>;
    readonly properties: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly value: string;
    }>;
    readonly type: "date";
  }>;
  readonly details: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "details";
  }>;
  readonly emojiInput: Readonly<{
    readonly construction: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly properties: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly type: "emojiInput";
  }>;
  readonly equation: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly latex?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly latex: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "equation";
  }>;
  readonly file: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly name?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly name?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly type: "file";
  }>;
  readonly footnoteDefinition: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly ref: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly ref: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "footnoteDefinition";
  }>;
  readonly footnoteInput: Readonly<{
    readonly construction: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly properties: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly type: "footnoteInput";
  }>;
  readonly footnote: Readonly<{
    readonly construction: Readonly<{
      readonly ref: string;
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly ref: string;
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "footnoteReference";
  }>;
  readonly heading: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly level: 1 | 2 | 3 | 4 | 5 | 6;
      readonly lineHeight?: number | string;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly level: 1 | 2 | 3 | 4 | 5 | 6;
      readonly lineHeight?: number | string;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
    }>;
    readonly type: "heading";
  }>;
  readonly horizontalRule: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "horizontalRule";
  }>;
  readonly image: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly alt?: string;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly naturalHeight?: number;
      readonly naturalWidth?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly title?: string;
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly alt?: string;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly naturalHeight?: number;
      readonly naturalWidth?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly title?: string;
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly type: "image";
  }>;
  readonly inlineEquation: Readonly<{
    readonly construction: Readonly<{
      readonly latex?: string;
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly latex: string;
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "inlineEquation";
  }>;
  readonly link: Readonly<{
    readonly construction: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly target?: string;
      readonly url: string;
    }>;
    readonly properties: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly target?: string;
      readonly url: string;
    }>;
    readonly type: "link";
  }>;
  readonly mediaEmbed: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly provider?: string;
      readonly sourceUrl?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly provider?: string;
      readonly sourceUrl?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly type: "mediaEmbed";
  }>;
  readonly mention: Readonly<{
    readonly construction: Readonly<{
      readonly label?: string;
      readonly ref: string;
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly label?: string;
      readonly ref: string;
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "mention";
  }>;
  readonly mentionInput: Readonly<{
    readonly construction: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly properties: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly type: "mentionInput";
  }>;
  readonly paragraph: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly lineHeight?: number | string;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly checked?: boolean;
      readonly indent?: number;
      readonly lineHeight?: number | string;
      readonly listRestart?: number;
      readonly listStart?: number;
      readonly listStyle?: string;
      readonly listType?: "bulleted" | "numbered" | "task";
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
    }>;
    readonly toggle: true;
    readonly type: "paragraph";
  }>;
  readonly placeholder: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly mediaType: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly mediaType: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "placeholder";
  }>;
  readonly slashInput: Readonly<{
    readonly construction: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly properties: Readonly<{
      readonly suggestion?: boolean;
      readonly suggestionData?: { readonly id: string; readonly createdAt: number; readonly type: "insert"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "remove"; readonly userId: string; } | { readonly id: string; readonly createdAt: number; readonly type: "update"; readonly userId: string; readonly newProperties?: unknown; readonly properties?: unknown; };
      readonly suggestionTransient?: boolean;
      readonly trigger?: string;
      readonly userId?: string;
      readonly value?: string;
    }>;
    readonly type: "slashInput";
  }>;
  readonly detailsSummary: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly toggle: true;
    readonly type: "summary";
  }>;
  readonly table: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly columnWidths?: readonly (null | number)[];
      readonly marginLeft?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly columnWidths?: readonly (null | number)[];
      readonly marginLeft?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "table";
  }>;
  readonly tableCell: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly backgroundColor?: string;
      readonly borders?: { readonly bottom?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly left?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly right?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly top?: { readonly color?: string; readonly style?: string; readonly width?: number; }; };
      readonly colSpan?: number;
      readonly header?: boolean;
      readonly rowSpan?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly backgroundColor?: string;
      readonly borders?: { readonly bottom?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly left?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly right?: { readonly color?: string; readonly style?: string; readonly width?: number; }; readonly top?: { readonly color?: string; readonly style?: string; readonly width?: number; }; };
      readonly colSpan?: number;
      readonly header?: boolean;
      readonly rowSpan?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "tableCell";
  }>;
  readonly tableRow: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly height?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly height?: number;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "tableRow";
  }>;
  readonly toc: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
    }>;
    readonly type: "toc";
  }>;
  readonly video: Readonly<{
    readonly construction: Readonly<{
      readonly aiPreview?: boolean;
      readonly provider?: string;
      readonly sourceUrl?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly properties: Readonly<{
      readonly aiPreview?: boolean;
      readonly provider?: string;
      readonly sourceUrl?: string;
      readonly suggestion?: { readonly id: string; readonly createdAt: number; readonly type: "insert" | "remove"; readonly userId: string; readonly isLineBreak?: boolean; };
      readonly suggestionTransient?: boolean;
      readonly textAlign?: "center" | "end" | "justify" | "left" | "right" | "start";
      readonly url: string;
      readonly width?: number | string;
    }>;
    readonly type: "video";
  }>;
}>;
type Types = Readonly<{
  element: EditorElement;
  mutations: Mutations;
  schema: Schema;
  text: EditorText;
  value: Value;
}>;

export const schema = Object.freeze({
  plugins: Object.freeze({
    paragraph: Object.freeze({ type: "paragraph" }),
    ai: Object.freeze({ key: "ai" }),
    suggestion: Object.freeze({ key: "suggestion" }),
    aiChat: Object.freeze({ type: "aiChat" }),
    heading: Object.freeze({ type: "heading" }),
    blockquote: Object.freeze({ type: "blockquote" }),
    horizontalRule: Object.freeze({ type: "horizontalRule" }),
    codeLine: Object.freeze({ type: "codeLine" }),
    codeBlock: Object.freeze({ type: "codeBlock" }),
    codeSyntax: Object.freeze({ key: "codeSyntax" }),
    tableCell: Object.freeze({ type: "tableCell" }),
    tableRow: Object.freeze({ type: "tableRow" }),
    table: Object.freeze({ type: "table" }),
    detailsSummary: Object.freeze({ type: "summary" }),
    details: Object.freeze({ type: "details" }),
    toc: Object.freeze({ type: "toc" }),
    image: Object.freeze({ type: "image" }),
    mediaEmbed: Object.freeze({ type: "mediaEmbed" }),
    video: Object.freeze({ type: "video" }),
    audio: Object.freeze({ type: "audio" }),
    file: Object.freeze({ type: "file" }),
    placeholder: Object.freeze({ type: "placeholder" }),
    callout: Object.freeze({ type: "callout" }),
    column: Object.freeze({ type: "column" }),
    columnGroup: Object.freeze({ type: "columnGroup" }),
    inlineEquation: Object.freeze({ type: "inlineEquation" }),
    equation: Object.freeze({ type: "equation" }),
    date: Object.freeze({ type: "date" }),
    link: Object.freeze({ type: "link" }),
    mentionInput: Object.freeze({ type: "mentionInput" }),
    mention: Object.freeze({ type: "mention" }),
    footnoteInput: Object.freeze({ type: "footnoteInput" }),
    footnote: Object.freeze({ type: "footnoteReference" }),
    footnoteDefinition: Object.freeze({ type: "footnoteDefinition" }),
    bold: Object.freeze({ key: "bold" }),
    italic: Object.freeze({ key: "italic" }),
    underline: Object.freeze({ key: "underline" }),
    code: Object.freeze({ key: "code" }),
    strikethrough: Object.freeze({ key: "strikethrough" }),
    script: Object.freeze({ key: "script" }),
    highlight: Object.freeze({ key: "highlight" }),
    kbd: Object.freeze({ key: "kbd" }),
    color: Object.freeze({ key: "color" }),
    backgroundColor: Object.freeze({ key: "backgroundColor" }),
    fontSize: Object.freeze({ key: "fontSize" }),
    fontFamily: Object.freeze({ key: "fontFamily" }),
    indent: Object.freeze({ key: "indent" }),
    textAlign: Object.freeze({ key: "textAlign" }),
    lineHeight: Object.freeze({ key: "lineHeight" }),
    comment: Object.freeze({ key: "comment" }),
    slashInput: Object.freeze({ type: "slashInput" }),
    emojiInput: Object.freeze({ type: "emojiInput" }),
  }),
  properties: Object.freeze({}),
}) satisfies Schema;

export const fingerprint = "fnv1a64:7b514f094be6c65e";

type EditorPlugins = (typeof EditorModule)["EditorKit"] & GeneratedEditorTypeProvider<Types>;

export type Editor = BaseEditor<Value, readonly [], EditorPlugins>;
