export type { Editor, Value } from '../interfaces/editor';

export {
  above,
  addMark,
  after,
  before,
  bookmark,
  collapse,
  defineEditorExtension,
  delete,
  deleteBackward,
  deleteForward,
  deleteFragment,
  deselect,
  edges,
  elementReadOnly,
  extend,
  first,
  fragment,
  getChildren,
  getCollabStatePatches,
  getDirtyPaths,
  getExtensionRegistry,
  getFragment,
  getLastCommit,
  getOperationDirtiness,
  getOperations,
  getPathByRuntimeId,
  getRuntimeId,
  getSelection,
  getSnapshot,
  hasBlocks,
  hasInlines,
  hasPath,
  hasTexts,
  insertBreak,
  insertFragment,
  insertNode,
  insertNodes,
  insertSoftBreak,
  insertText,
  isBlock,
  isEdge,
  isEditor,
  isElementReadOnly,
  isEmpty,
  isEnd,
  isInline,
  isNormalizing,
  isSelectable,
  isStart,
  isVoid,
  last,
  leaf,
  levels,
  liftNodes,
  mergeNodes,
  move,
  moveNodes,
  next,
  normalize,
  parent,
  path,
  pathRef,
  pathRefs,
  point,
  pointRef,
  pointRefs,
  positions,
  previous,
  projectRange,
  range,
  rangeRef,
  rangeRefs,
  read,
  registerCapability,
  registerCommitListener,
  registerNormalizer,
  removeMark,
  removeNodes,
  replace,
  reset,
  select,
  setNodes,
  setNormalizing,
  setPoint,
  setSelection,
  shouldMergeNodesRemovePrevNode,
  splitNodes,
  string,
  subscribe,
  subscribeCommit,
  subscribeSource,
  toggleMark,
  unhangRange,
  unsetNodes,
  update,
  void,
  withoutNormalizing,
  wrapNodes,
} from '../interfaces/editor';

export {
  defineCommand,
  executeCommand,
  registerCommand,
} from '../core/command-registry';
export {
  getEditorRuntime,
  setEditorRuntime,
} from '../core/editor-runtime';
export {
  getExtensionRegistry as getEditorExtensionRegistry,
  inheritExtensionRegistry as inheritEditorExtensionRegistry,
} from '../core/extension-registry';
export {
  applyOperation,
  applyStatePatches,
  getCachedFullRootReplaceTopLevelRuntimeIds,
  getCurrentMarks as getEditorCurrentMarks,
  getCurrentSelectionRoot as getEditorSelectionRoot,
  getEditorOperationRoot,
  getLiveNode as getEditorLiveNode,
  getLiveSelection as getEditorLiveSelection,
  getLiveText as getEditorLiveText,
  getOperationCount,
  getSnapshotVersion,
  markInternalOwnedReplayOperation,
  setChildren as setEditorChildren,
  setCurrentMarks as setEditorMarks,
  setCurrentSelection as setEditorSelection,
  setTargetRuntime as setEditorTargetRuntime,
  shouldSaveStatePatch,
  withOperationRootChildren,
} from '../core/public-state';
export { hasTransformMiddleware as hasEditorTransformMiddleware } from '../core/transform-middleware';
export {
  getEditorTransformRegistry,
  setEditorTransformRegistry,
} from '../core/transform-registry';
export { projectRangeInSnapshot } from '../range-projection';
export { formatDebugValue } from '../utils/format-debug-value';
export { isObject } from '../utils/is-object';
export {
  getOperationRoot,
  getRangeRoot,
  MAIN_ROOT_KEY,
} from './root-location';
