export type { Editor, Value } from '../interfaces/editor';

export { failInvariant } from './fail-invariant';

export {
  above,
  addMark,
  after,
  before,
  collapse,
  defineEditorExtension,
  delete,
  deleteBackward,
  deleteForward,
  deleteFragment,
  deselect,
  edges,
  elementReadOnly,
  extend,
  first,
  fragment,
  getChildren,
  getCollabEffects,
  getExtensionRegistry,
  getFragment,
  getLastCommit,
  getPathByRuntimeId,
  getRuntimeId,
  getSelection,
  getSnapshot,
  hasBlocks,
  hasInlines,
  hasPath,
  hasTexts,
  insertBreak,
  insertNode,
  insertNodes,
  insertSoftBreak,
  insertText,
  isBlock,
  isEdge,
  isEditor,
  isElementReadOnly,
  isEmpty,
  isEnd,
  isInline,
  isSelectable,
  isStart,
  isVoid,
  last,
  leaf,
  levels,
  liftNodes,
  mergeNodes,
  move,
  moveNodes,
  next,
  parent,
  path,
  point,
  positions,
  previous,
  projectRange,
  range,
  read,
  removeMark,
  removeNodes,
  replaceChildren,
  replace,
  reset,
  select,
  setNodes,
  setPoint,
  setSelection,
  shouldMergeNodesRemovePrevNode,
  splitNodes,
  string,
  subscribe,
  subscribeCommit,
  subscribeSource,
  toggleBlock,
  toggleMark,
  unhangRange,
  unsetNodes,
  unwrapNodes,
  update,
  void,
  wrapNodes,
} from '../interfaces/editor';

export {
  defineCommand,
  dispatchCommand,
  hasCommandHandler,
} from '../core/command-registry';
export { createDetachedContentSlice } from '../core/content-slice';
export type { InternalEditorRuntimeElementEntry } from '../core/snapshot-index';
export { editorCommands } from '../core/editor-commands';
export {
  createInternalDocumentChange,
  getInternalDocumentChangeClassification,
  getInternalDocumentChangeClassificationEntries,
  getInternalDocumentChangeEntries,
  getInternalDocumentChangeSet,
  mapInternalDocumentChangePosition,
  getDocumentChangeRelocations,
  getExactDocumentChangeRelocations,
  IndexedDocument,
  type DocumentChangeRelocation,
} from '../core/document-change';
export {
  createInternalClipboardApi,
  initializeEditorExtensions,
} from '../create-editor';
export {
  areEditorSchemaIdentitiesEqual,
  compileEditorSchemaContributions,
  EditorSchemaCompileError,
  getCompiledSchemaPropertyId,
  getCompiledPropertyMergeStrategy,
  matchesCompiledSchemaTarget,
  readEditorSchemaIdentity,
  resolveCompiledSchemaProperty,
  type CompiledEditorSchema,
  type CompiledSchemaConstructionPlan,
  type CompiledSchemaContentProgram,
  type CompiledSchemaElement,
  type CompiledSchemaProperty,
  type CompiledSchemaPropertyMergeStrategy,
  type CompiledSchemaTargetContext,
  type EditorSchemaContributionRecord,
  type EditorSchemaDiagnostic,
} from '../core/schema-compiler';
export {
  getCompiledEditorConfiguration,
  getInstalledEditorExtension,
  reportEditorLifecycleError,
} from '../core/editor-extension';
export { isPropertyPolicyToken } from '../interfaces/property-policy';
export {
  assertPublicRootKey,
  toInternalRoot,
  toPublicRoot,
} from '../core/public-root';
export { getCompiledEditorSchemaFromApi } from '../core/editor-schema';
export {
  getEditorRuntime,
  getEditorRuntimeOwner,
  hasEditorRuntime,
  setEditorRuntime,
} from '../core/editor-runtime';
export {
  getCompiledEditorSchema,
  getExtensionRegistry as getEditorExtensionRegistry,
  inheritExtensionRegistry as inheritEditorExtensionRegistry,
} from '../core/extension-registry';
export {
  applyBuiltDocumentChange,
  getActiveEditorTransaction,
  getCollabEffectTypes,
  getCurrentMarks as getEditorCurrentMarks,
  getCurrentSelectionRoot as getEditorSelectionRoot,
  getEditorDefaultBlockType,
  getEditorMaxLength,
  getEditorRuntimeElementEntries,
  getEditorRuntimeRootKeys,
  getEditorStateView,
  getEditorUpdateRoot,
  getEditorRuntimeIdForNode,
  getLiveNode as getEditorLiveNode,
  getLiveSelection as getEditorLiveSelection,
  getLiveText as getEditorLiveText,
  getSnapshotVersion,
  getStateFieldEffectTypes,
  runTrustedUpdate,
  scheduleAfterCommitNotification,
  setChildren as setEditorChildren,
  setEditorComposing,
  setEditorDefaultBlockType,
  setEditorFocused,
  setEditorMaxLength,
  setEditorReadOnly,
  setCurrentMarks as setEditorMarks,
  setCurrentSelection as setEditorSelection,
  setTargetRuntime as setEditorTargetRuntime,
  subscribeEditorViewState,
  toEditorCoreStateView,
  withEditorUpdateRootScope,
} from '../core/public-state';
export { projectRangeInSnapshot } from '../range-projection';
export {
  assertSelectionSupported,
  decodeEditorSelection,
  encodeEditorSelection,
  mapSelectionThroughChange,
} from '../core/selection-protocol';
export { createEditorEffect } from '../core/transaction-values';
export {
  areEditorJsonValuesEqual,
  assertEditorJsonValue,
  decodeEditorEffect,
  decodeVersionedValue,
  encodeEditorEffect,
  encodeVersionedValue,
} from '../core/value-codec';
export { formatDebugValue } from '../utils/format-debug-value';
export { isObject } from '../utils/is-object';
export { getRangeRoot, MAIN_ROOT_KEY } from './root-location';
