export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './excalidrawValue';
export * from './initialDataExcalidraw';
`;

export const indexFile = {
  '/excalidraw/index.ts': indexCode,
};
