export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './AlignToolbarButtons';
export * from './alignPlugin';
export * from './alignValue';
`;

export const indexFile = {
  '/align/index.ts': indexCode,
};
