blank_issues_enabled: false
contact_links:
  - name: "💬 Support: Discussions"
    url: https://github.com/udecode/plate/discussions
    about: Share ideas, ask and answer questions in our Discussions.
  - name: "💬 Support: Discord"
    url: https://discord.gg/mAZRuBzGM3
    about: Feels more chatty? Ask quick questions in our Discord.