import { defineConfig } from 'tsup';

export default defineConfig({
  clean: true,
  dts: true,
  entry: ['src/index.ts'],
  format: ['esm'],
  sourcemap: true,
  minify: false,
  target: 'esnext',
  outDir: 'dist',
  treeshake: true,
  external: [
    'commander',
    'prompts',
    'sisteransi',
    'mimic',
    'onetime',
    'signal',
    'cli',
    'clone',
    'defaults',
    'wcwidth',
    'readable',
    'inherits',
    'util',
    'safe',
    'string_decoder',
    'bl',
    'kleur',
    'ora',
    'restore',
    'log',
    'is',
    'stdin',
  ],
});
