export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './BasicElementToolbarButtons';
export * from './basicElementPlugins';
export * from './basicElementsValue';
`;

export const indexFile = {
  '/basic-elements/index.ts': indexCode,
};
