import {
  AlignCenterIcon,
  ArrowDownToLineIcon,
  ArrowRightToLineIcon,
  AtSignIcon,
  AudioLinesIcon,
  BoldIcon,
  BrickWallIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CaptionsIcon,
  CheckSquareIcon,
  ChevronRightSquareIcon,
  ChevronsUpDownIcon,
  CircleGaugeIcon,
  CodeIcon,
  CodeXmlIcon,
  Columns3Icon,
  CommandIcon,
  DockIcon,
  Edit3Icon,
  EllipsisIcon,
  EyeIcon,
  FileCodeIcon,
  FileIcon,
  FilesIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  FilmIcon,
  FrameIcon,
  GripVerticalIcon,
  HandIcon,
  HashIcon,
  Heading1Icon,
  HelpCircleIcon,
  HighlighterIcon,
  HistoryIcon,
  ImageIcon,
  IndentIcon,
  ItalicIcon,
  KeyboardIcon,
  LayersIcon,
  LightbulbIcon,
  LinkIcon,
  ListIcon,
  ListTodoIcon,
  LoaderCircleIcon,
  LogOutIcon,
  MenuIcon,
  MessageSquareIcon,
  MessageSquareTextIcon,
  MinusIcon,
  MonitorIcon,
  MousePointerClickIcon,
  MoveVerticalIcon,
  PaintRollerIcon,
  PaletteIcon,
  PanelTopIcon,
  PencilRulerIcon,
  PercentIcon,
  PilcrowIcon,
  PlusSquareIcon,
  ProportionsIcon,
  QuoteIcon,
  RadicalIcon,
  RectangleEllipsisIcon,
  RectangleHorizontalIcon,
  ReplaceIcon,
  SeparatorHorizontalIcon,
  ServerIcon,
  SlashIcon,
  SmileIcon,
  SparklesIcon,
  SplitSquareVerticalIcon,
  SquareDashedIcon,
  SquareMIcon,
  SquareMinusIcon,
  SquareMousePointerIcon,
  SquareStackIcon,
  StrikethroughIcon,
  SubscriptIcon,
  SuperscriptIcon,
  TableIcon,
  TableOfContentsIcon,
  TagIcon,
  TagsIcon,
  TextCursorInputIcon,
  TextSearchIcon,
  UnderlineIcon,
  UploadIcon,
  UserIcon,
  UsersIcon,
} from 'lucide-react';

import type { SidebarNavItem } from '@/types/nav';

export const DocIcons = {
  ai: SparklesIcon,
  'ai-menu': SparklesIcon,
  'ai-toolbar-button': SparklesIcon,
  'alert-dialog': SquareStackIcon,
  'align-toolbar-button': AlignCenterIcon,
  autoformat: PercentIcon,
  avatar: UserIcon,
  'basic-blocks': Heading1Icon,
  'basic-editor-default': KeyboardIcon,
  'basic-editor-handler': HandIcon,
  'basic-editor-styling': PaletteIcon,
  'basic-editor-value': FilesIcon,
  'basic-marks': BoldIcon,
  'basic-nodes': Heading1Icon,
  'basic-plugins-components': MonitorIcon,
  'basic-plugins-default': LayersIcon,
  'block-menu': MenuIcon,
  'block-list': ListTodoIcon,
  'node-selection': SquareMousePointerIcon,
  blockquote: QuoteIcon,
  bold: BoldIcon,
  button: SquareMinusIcon,
  calendar: CalendarDaysIcon,
  callout: LightbulbIcon,
  caption: CaptionsIcon,
  checkbox: CheckSquareIcon,
  code: CodeIcon,
  'code-block': FileCodeIcon,
  collaboration: UsersIcon,
  'collaboration-demo': UsersIcon,
  column: Columns3Icon,
  combobox: SlashIcon,
  command: CommandIcon,
  comment: MessageSquareTextIcon,
  'comment-node': MessageSquareTextIcon,
  'comment-toolbar-button': MessageSquareTextIcon,
  'context-menu': MousePointerClickIcon,
  copilot: ArrowRightToLineIcon,
  csv: FileSpreadsheetIcon,
  'cursor-overlay': TextCursorInputIcon,
  date: CalendarIcon,
  default: CodeXmlIcon,
  dialog: SquareStackIcon,
  dnd: GripVerticalIcon,
  docx: FileTextIcon,
  draggable: GripVerticalIcon,
  'dropdown-menu': ChevronsUpDownIcon,
  'editable-voids': Edit3Icon,
  editor: FileTextIcon,
  emoji: SmileIcon,
  'emoji-dropdown-menu': SmileIcon,
  equation: RadicalIcon,
  excalidraw: PencilRulerIcon,
  'exit-break': LogOutIcon,
  'find-replace': TextSearchIcon,
  'fixed-toolbar': PanelTopIcon,
  'floating-toolbar': RectangleEllipsisIcon,
  font: PaintRollerIcon,
  'font-color-toolbar-button': PaintRollerIcon,
  'forced-layout': BrickWallIcon,
  heading: Heading1Icon,
  highlight: HighlighterIcon,
  'history-toolbar-button': HistoryIcon,
  'horizontal-rule': MinusIcon,
  html: FileCodeIcon,
  'hundreds-editors': CircleGaugeIcon,
  'huge-document': CircleGaugeIcon,
  iframe: FrameIcon,
  indent: IndentIcon,
  'indent-toolbar-button': ListIcon,
  'inline-combobox': SlashIcon,
  input: RectangleHorizontalIcon,
  'insert-toolbar-button': PlusSquareIcon,
  italic: ItalicIcon,
  kbd: KeyboardIcon,
  'line-height': MoveVerticalIcon,
  'line-height-toolbar-button': MoveVerticalIcon,
  link: LinkIcon,
  'link-toolbar': LinkIcon,
  'link-toolbar-button': LinkIcon,
  list: ListIcon,
  'list-toolbar-button': ListIcon,
  'mark-toolbar-button': BoldIcon,
  markdown: SquareMIcon,
  'markdown-streaming': SquareMIcon,
  'markdown-to-plite': SquareMIcon,
  media: ImageIcon,
  'media-audio': AudioLinesIcon,
  'media-embed': DockIcon,
  'media-file': FileIcon,
  'media-image': ImageIcon,
  'media-placeholder': SquareDashedIcon,
  'media-preview-dialog': ImageIcon,
  'media-toolbar': ImageIcon,
  'media-toolbar-button': ImageIcon,
  'media-video': FilmIcon,
  mention: AtSignIcon,
  'mode-toolbar-button': EyeIcon,
  'more-toolbar-button': EllipsisIcon,
  'multi-select': TagsIcon,
  'multiple-editors': SplitSquareVerticalIcon,
  'node-id': HashIcon,
  paragraph: PilcrowIcon,
  playground: FileCodeIcon,
  popover: MessageSquareIcon,
  'preview-markdown': SquareMIcon,
  resizable: ProportionsIcon,
  'search-highlight': HighlighterIcon,
  select: KeyboardIcon,
  'select-editor': TagsIcon,
  separator: SeparatorHorizontalIcon,
  'server-side': ServerIcon,
  'single-block': RectangleHorizontalIcon,
  'slash-command': SlashIcon,
  spinner: LoaderCircleIcon,
  strikethrough: StrikethroughIcon,
  subscript: SubscriptIcon,
  superscript: SuperscriptIcon,
  tabbable: ArrowRightToLineIcon,
  table: TableIcon,
  'table-toolbar-button': TableIcon,
  tag: TagIcon,
  'text-align': AlignCenterIcon,
  textAlign: AlignCenterIcon,
  toc: TableOfContentsIcon,
  details: ChevronRightSquareIcon,
  'details-toolbar-button': ChevronRightSquareIcon,
  toolbar: PanelTopIcon,
  tooltip: HelpCircleIcon,
  'trailing-block': ArrowDownToLineIcon,
  'turn-into-toolbar-button': ReplaceIcon,
  underline: UnderlineIcon,
  upload: UploadIcon,
  'version-history': HistoryIcon,
};

export const getDocIcon = (item: SidebarNavItem, category?: string) => {
  if (category === 'guide') return null;

  const icon = item.icon ?? item.href?.split('/').pop();

  if (icon && icon in DocIcons) {
    return DocIcons[icon as keyof typeof DocIcons];
  }

  return category === 'api' ? CodeXmlIcon : null;
};
