/**
 * @file Automatically generated by barrelsby.
 */

export * from './StrikethroughPlugin';
export * from './defaults';
export * from './deserializeStrikethrough';
export * from './renderLeafStrikethrough';
export * from './types';
