export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './mentionValue';
export * from './mentionables';
`;

export const indexFile = {
  '/mention/index.ts': indexCode,
};
