/** @file Automatically generated by barrelsby. */

export * from './createPlateEditor';

export * from './createReactPlugin';

export * from './hotkeys';

export * from './setPlatePlugins';

export * from './withPlate';
