export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './getNodesWithRandomId';
export * from './withStyledDraggables';
`;

export const indexFile = {
  '/dnd/index.ts': indexCode,
};
