export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './HighlightToolbarButton';
export * from './highlightValue';
`;

export const indexFile = {
  '/highlight/index.ts': indexCode,
};
