export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './exitBreakPlugin';
export * from './exitBreakValue';
`;

export const indexFile = {
  '/exit-break/index.ts': indexCode,
};
