export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './ListToolbarButtons';
export * from './createList';
export * from './listValue';
`;

export const indexFile = {
  '/list/index.ts': indexCode,
};
