export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './createPreviewPlugin';
export * from './decoratePreview';
export * from './previewMdValue';
export * from './renderLeafPreview';
export * from './PreviewLeaf/index';
`;

export const indexFile = {
  '/preview-markdown/index.ts': indexCode,
};
