import type { Registry } from './schema';

export const examples: Registry = [
  {
    files: ['example/editor-default.tsx'],
    name: 'editor-default',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/editor-disabled.tsx'],
    name: 'editor-disabled',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/editor-ghost.tsx'],
    name: 'editor-ghost',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/editor-label.tsx'],
    name: 'editor-label',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/editor-text.tsx'],
    name: 'editor-text',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/editor-button.tsx'],
    name: 'editor-button',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/editor-form.tsx'],
    name: 'editor-form',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/basic-editor-default-demo.tsx'],
    name: 'basic-editor-default-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/controlled-demo.tsx'],
    name: 'controlled-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/basic-editor-styling-demo.tsx'],
    name: 'basic-editor-styling-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/basic-editor-handler-demo.tsx'],
    name: 'basic-editor-handler-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/basic-editor-value-demo.tsx'],
    name: 'basic-editor-value-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/basic-plugins-components-demo.tsx'],
    name: 'basic-plugins-components-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/basic-plugins-default-demo.tsx'],
    name: 'basic-plugins-default-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/cloud-demo.tsx'],
    name: 'cloud-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/editable-voids-demo.tsx'],
    name: 'editable-voids-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/find-replace-demo.tsx'],
    name: 'find-replace-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/hundreds-blocks-demo.tsx'],
    name: 'hundreds-blocks-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/hundreds-editors-demo.tsx'],
    name: 'hundreds-editors-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/iframe-demo.tsx'],
    name: 'iframe-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/mode-toggle.tsx'],
    name: 'mode-toggle',
    type: 'registry:example',
  },
  {
    files: ['example/multiple-editors-demo.tsx'],
    name: 'multiple-editors-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/version-history-demo.tsx'],
    name: 'version-history-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/playground-demo.tsx'],
    name: 'playground-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    files: ['example/preview-md-demo.tsx'],
    name: 'preview-md-demo',
    registryDependencies: [],
    type: 'registry:example',
  },
  {
    external: true,
    files: ['styles/globals.css'],
    name: 'globals',
    type: 'registry:style',
  },
  {
    external: true,
    files: ['types/plate-types.ts'],
    name: 'plate-types',
    type: 'registry:lib',
  },
];
