import type { Registry } from '@/registry/schema';

const plugins: Registry = [
  {
    dependencies: [
      '@udecode/plate-callout',
      '@udecode/plate-date',
      '@udecode/plate-docx',
      '@udecode/plate-emoji',
      '@udecode/plate-font',
      '@udecode/plate-highlight',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-juice',
      '@udecode/plate-kbd',
      '@udecode/plate-layout',
      '@udecode/plate-markdown',
      '@udecode/plate-math',
      '@udecode/plate-slash-command',
      '@udecode/plate-toggle',
      '@udecode/plate-trailing-block',
    ],
    files: ['components/editor/plugins/editor-plugins.tsx'],
    name: 'editor-plugins',
    registryDependencies: [
      'ai-plugins',
      'basic-nodes-plugins',
      'align-plugin',
      'autoformat-plugin',
      'block-menu-plugins',
      'comments-plugin',
      'delete-plugins',
      'dnd-plugins',
      'exit-break-plugin',
      'indent-list-plugins',
      'line-height-plugin',
      'link-plugin',
      'media-plugins',
      'mention-plugin',
      'reset-block-type-plugin',
      'soft-break-plugin',
      'table-plugin',
      'toc-plugin',
    ],
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-ai',
      '@udecode/plate-basic-marks',
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-heading',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-link',
      '@udecode/plate-markdown',
      '@udecode/plate-selection',
    ],
    files: ['components/editor/plugins/ai-plugins.tsx'],
    name: 'ai-plugins',
    registryDependencies: [
      'basic-nodes-plugins',
      'indent-list-plugins',
      'link-plugin',
      'ai-menu',
      'blockquote-element',
      'code-block-element',
      'code-leaf',
      'code-line-element',
      'code-syntax-leaf',
      'cursor-overlay',
      'heading-element',
      'hr-element',
      'link-element',
      'paragraph-element',
    ],
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-alignment',
      '@udecode/plate-heading',
      '@udecode/plate-media',
    ],
    files: ['components/editor/plugins/align-plugin.ts'],
    name: 'align-plugin',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-autoformat',
      '@udecode/plate-basic-marks',
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-heading',
      '@udecode/plate-highlight',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-indent-list',
      '@udecode/plate-toggle',
    ],
    files: ['components/editor/plugins/autoformat-plugin.ts'],
    name: 'autoformat-plugin',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-autoformat',
      '@udecode/plate-basic-marks',
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-heading',
      '@udecode/plate-highlight',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-list',
      '@udecode/plate-toggle',
    ],
    files: ['components/editor/plugins/autoformat-list-plugin.ts'],
    name: 'autoformat-list-plugin',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-basic-marks',
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-heading',
      'prismjs',
    ],
    files: ['components/editor/plugins/basic-nodes-plugins.tsx'],
    name: 'basic-nodes-plugins',
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-selection'],
    files: ['components/editor/plugins/block-selection-plugins.ts'],
    name: 'block-selection-plugins',
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-selection'],
    files: ['components/editor/plugins/block-menu-plugins.ts'],
    name: 'block-menu-plugins',
    registryDependencies: ['block-context-menu', 'block-selection-plugins'],
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-comments'],
    files: ['components/editor/plugins/comments-plugin.tsx'],
    name: 'comments-plugin',
    registryDependencies: ['comments-popover'],
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-ai',
      '@udecode/plate-markdown',
      '@faker-js/faker',
    ],
    files: ['components/editor/plugins/copilot-plugins.ts'],
    name: 'copilot-plugins',
    registryDependencies: ['ghost-text'],
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-select',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-media',
    ],
    files: ['components/editor/plugins/delete-plugins.ts'],
    name: 'delete-plugins',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-dnd',
      '@udecode/plate-media',
      '@udecode/plate-node-id',
    ],
    files: ['components/editor/plugins/dnd-plugins.tsx'],
    name: 'dnd-plugins',
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-break', '@udecode/plate-heading'],
    files: ['components/editor/plugins/exit-break-plugin.ts'],
    name: 'exit-break-plugin',
    type: 'registry:component',
  },
  {
    dependencies: [],
    files: ['components/editor/plugins/fixed-toolbar-plugin.tsx'],
    name: 'fixed-toolbar-plugin',
    registryDependencies: ['fixed-toolbar', 'fixed-toolbar-buttons'],
    type: 'registry:component',
  },
  {
    dependencies: [],
    files: ['components/editor/plugins/fixed-toolbar-list-plugin.tsx'],
    name: 'fixed-toolbar-list-plugin',
    registryDependencies: ['fixed-toolbar', 'fixed-toolbar-buttons'],
    type: 'registry:component',
  },
  {
    dependencies: [],
    files: ['components/editor/plugins/floating-toolbar-plugin.tsx'],
    name: 'floating-toolbar-plugin',
    registryDependencies: ['floating-toolbar', 'floating-toolbar-buttons'],
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-heading',
      '@udecode/plate-indent',
      '@udecode/plate-indent-list',
      '@udecode/plate-toggle',
    ],
    files: ['components/editor/plugins/indent-list-plugins.ts'],
    name: 'indent-list-plugins',
    registryDependencies: ['indent-fire-marker', 'indent-todo-marker'],
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-heading', '@udecode/plate-line-height'],
    files: ['components/editor/plugins/line-height-plugin.ts'],
    name: 'line-height-plugin',
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-link'],
    files: ['components/editor/plugins/link-plugin.tsx'],
    name: 'link-plugin',
    registryDependencies: ['link-floating-toolbar'],
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-caption', '@udecode/plate-media'],
    files: ['components/editor/plugins/media-plugins.tsx'],
    name: 'media-plugins',
    registryDependencies: ['image-preview'],
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-mention'],
    files: ['components/editor/plugins/mention-plugin.ts'],
    name: 'mention-plugin',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-block-quote',
      '@udecode/plate-callout',
      '@udecode/plate-code-block',
      '@udecode/plate-heading',
      '@udecode/plate-indent-list',
      '@udecode/plate-reset-node',
    ],
    files: ['components/editor/plugins/reset-block-type-plugin.ts'],
    name: 'reset-block-type-plugin',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-break',
      '@udecode/plate-block-quote',
      '@udecode/plate-callout',
      '@udecode/plate-code-block',
      '@udecode/plate-table',
    ],
    files: ['components/editor/plugins/soft-break-plugin.ts'],
    name: 'soft-break-plugin',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-code-block',
      '@udecode/plate-tabbable',
      '@udecode/plate-table',
    ],
    files: ['components/editor/plugins/tabbable-plugin.ts'],
    name: 'tabbable-plugin',
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-table'],
    files: ['components/editor/plugins/table-plugin.ts'],
    name: 'table-plugin',
    type: 'registry:component',
  },
  {
    dependencies: ['@udecode/plate-heading'],
    files: ['components/editor/plugins/toc-plugin.ts'],
    name: 'toc-plugin',
    type: 'registry:component',
  },
];

export const components: Registry = [
  ...plugins,
  {
    dependencies: ['@udecode/plate-ai', 'ai', '@faker-js/faker'],
    files: [
      {
        path: 'components/editor/use-chat.tsx',
        type: 'registry:component',
      },
    ],
    name: 'use-chat',
    registryDependencies: ['button', 'dialog', 'input', 'command', 'popover'],
    type: 'registry:component',
  },
  {
    dependencies: ['@ai-sdk/openai', 'ai'],
    files: [
      {
        path: 'components/api/ai/command/route.ts',
        target: 'app/api/ai/command/route.ts',
        type: 'registry:page',
      },
      {
        path: 'components/api/ai/copilot/route.ts',
        target: 'app/api/ai/copilot/route.ts',
        type: 'registry:page',
      },
    ],
    name: 'api-ai',
    registryDependencies: ['use-chat'],
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-callout',
      '@udecode/plate-code-block',
      '@udecode/plate-date',
      '@udecode/plate-heading',
      '@udecode/plate-indent-list',
      '@udecode/plate-layout',
      '@udecode/plate-link',
      '@udecode/plate-math',
      '@udecode/plate-media',
      '@udecode/plate-table',
    ],
    files: ['components/editor/transforms.ts'],
    name: 'transforms',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-comments',
      '@udecode/plate-excalidraw',
      '@udecode/plate-heading',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-link',
      '@udecode/plate-media',
      '@udecode/plate-mention',
      '@udecode/plate-table',
      '@udecode/plate-toggle',
    ],
    files: ['components/editor/plate-types.ts'],
    name: 'plate-types',
    type: 'registry:component',
  },
  {
    dependencies: [
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-comments',
      '@udecode/plate-excalidraw',
      '@udecode/plate-heading',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-link',
      '@udecode/plate-list',
      '@udecode/plate-media',
      '@udecode/plate-mention',
      '@udecode/plate-table',
      '@udecode/plate-toggle',
    ],
    files: ['components/editor/plate-list-types.ts'],
    name: 'plate-list-types',
    type: 'registry:component',
  },
];
