import type { Registry } from 'shadcn/registry';

export const registryBlocks: Registry['items'] = [
  {
    categories: ['Editors'],
    dependencies: [
      '@udecode/cn',
      '@udecode/plate-ai',
      '@udecode/plate-basic-marks',
      '@udecode/plate-block-quote',
      '@udecode/plate-code-block',
      '@udecode/plate-comments',
      '@udecode/plate-callout',
      '@udecode/plate-suggestion',
      '@udecode/plate',
      '@udecode/plate-date',
      '@udecode/plate-emoji',
      '@emoji-mart/data@1.2.1',
      '@udecode/plate-excalidraw',
      '@udecode/plate-heading',
      '@udecode/plate-highlight',
      '@udecode/plate-horizontal-rule',
      '@udecode/plate-kbd',
      '@udecode/plate-layout',
      '@udecode/plate-link',
      '@udecode/plate-media',
      '@udecode/plate-mention',
      '@udecode/plate-slash-command',
      '@udecode/plate-table',
      '@udecode/plate-toggle',
      'sonner',
    ],
    description: 'An AI editor',
    files: [
      {
        path: 'blocks/editor-ai/page.tsx',
        target: 'app/editor/page.tsx',
        type: 'registry:page',
      },
      {
        path: 'blocks/editor-ai/components/editor/plate-editor.tsx',
        type: 'registry:component',
      },
      {
        path: 'blocks/editor-ai/components/editor/use-create-editor.ts',
        type: 'registry:component',
      },
      {
        path: 'components/editor/settings.tsx',
        type: 'registry:component',
      },
    ],
    name: 'editor-ai',
    registryDependencies: [
      'plate-ui',
      'ai-api',
      'media-uploadthing-api',
      'plate-types',

      'editor-plugins',
      'copilot-plugins',
      'floating-toolbar-plugin',
      'fixed-toolbar-plugin',

      'ai-menu',
      'ghost-text',
      'block-discussion',
      'cursor-overlay',
      'editor',
      'block-context-menu',

      'ai-node',
      'blockquote-node',
      'block-draggable',
      'block-placeholder',
      'code-block-node',
      'code-node',
      'column-node',
      'comment-node',
      'callout-node',
      'suggestion-node',
      'date-node',
      'equation-node',
      'emoji-input-node',
      'excalidraw-node',
      'heading-node',
      'highlight-node',
      'hr-node',
      'kbd-node',
      'link-node',
      'media-audio-node',
      'media-embed-node',
      'media-image-node',
      'media-file-node',
      'media-placeholder-node',
      'media-video-node',
      'mention-node',
      'mention-input-node',
      'paragraph-node',
      'slash-input-node',
      'table-node',
      'toc-node',
      'toggle-node',
    ],
    type: 'registry:block',
  },
  {
    categories: ['Editors'],
    dependencies: ['@udecode/cn'],
    description: 'A multi-select editor',
    files: [
      {
        path: 'blocks/editor-select/page.tsx',
        target: 'app/editor/page.tsx',
        type: 'registry:page',
      },
    ],
    meta: {
      descriptionSrc: '/docs/multi-select',
    },
    name: 'editor-select',
    registryDependencies: ['plate-ui', 'select-editor-demo'],
    type: 'registry:block',
  },
  {
    categories: ['Editors'],
    dependencies: [
      '@udecode/cn',
      '@udecode/plate-basic-elements',
      '@udecode/plate-basic-marks',
    ],
    description: 'A basic editor',
    files: [
      {
        path: 'blocks/editor-basic/page.tsx',
        target: 'app/editor/page.tsx',
        type: 'registry:page',
      },
      {
        path: 'blocks/editor-basic/components/editor/plate-editor.tsx',
        type: 'registry:component',
      },
      {
        path: 'blocks/editor-basic/components/editor/use-create-editor.ts',
        type: 'registry:component',
      },
    ],
    name: 'editor-basic',
    registryDependencies: ['plate-ui', 'editor'],
    type: 'registry:block',
  },
  {
    categories: ['Serializers'],
    dependencies: ['@udecode/cn'],
    files: [
      {
        path: 'blocks/slate-to-html/page.tsx',
        target: 'app/html/page.tsx',
        type: 'registry:page',
      },
      {
        path: 'components/editor/slate-to-html.tsx',
        type: 'registry:component',
      },
      {
        path: 'lib/create-html-document.ts',
        type: 'registry:lib',
      },
    ],
    meta: {
      rsc: true,
    },
    name: 'slate-to-html',
    registryDependencies: ['plate-ui'],
    type: 'registry:block',
  },
];
