import {
  arrows,
  basicElements,
  basicLists,
  basicMarks,
  legal,
  legalHtml,
  mathComparison,
  mathEquality,
  mathFraction,
  mathSubscriptNumbers,
  mathSubscriptSymbols,
  mathSuperscriptNumbers,
  mathSuperscriptSymbols,
  mathOperations,
  mathMultiplication,
  mathDivision,
  punctuation,
  WithAutoformatOptions,
} from './autoFormatRules';

export const optionsAutoFormat: WithAutoformatOptions = {
  rules: [
    ...basicElements,
    ...basicLists,
    ...basicMarks,
    ...punctuation,
    ...legal,
    ...legalHtml,
    ...arrows,
    ...mathComparison,
    ...mathEquality,
    ...mathOperations,
    ...mathMultiplication,
    ...mathDivision,
    ...mathFraction,
    ...mathSuperscriptSymbols,
    ...mathSubscriptSymbols,
    ...mathSuperscriptNumbers,
    ...mathSubscriptNumbers,
  ],
};
