module.exports = {
  ...require('./aliases-plate'),
  '@udecode/plate': 'plate',
  '@udecode/plate-styled-components': 'ui/styled-components',
  '@udecode/plate-ui': 'ui/plate',
  '@udecode/plate-ui-alignment': 'ui/nodes/alignment',
  '@udecode/plate-ui-block-quote': 'ui/nodes/block-quote',
  '@udecode/plate-ui-button': 'ui/button',
  '@udecode/plate-ui-code-block': 'ui/nodes/code-block',
  '@udecode/plate-ui-combobox': 'ui/combobox',
  '@udecode/plate-ui-cursor': 'ui/cursor',
  '@udecode/plate-ui-dnd': 'ui/dnd',
  '@udecode/plate-ui-find-replace': 'ui/find-replace',
  '@udecode/plate-ui-font': 'ui/nodes/font',
  '@udecode/plate-ui-horizontal-rule': 'ui/nodes/horizontal-rule',
  '@udecode/plate-ui-image': 'ui/nodes/image',
  '@udecode/plate-ui-line-height': 'ui/nodes/line-height',
  '@udecode/plate-ui-link': 'ui/nodes/link',
  '@udecode/plate-ui-list': 'ui/nodes/list',
  '@udecode/plate-ui-media-embed': 'ui/nodes/media-embed',
  '@udecode/plate-ui-mention': 'ui/nodes/mention',
  '@udecode/plate-ui-placeholder': 'ui/placeholder',
  '@udecode/plate-ui-popover': 'ui/popover',
  '@udecode/plate-ui-table': 'ui/nodes/table',
  '@udecode/plate-ui-toolbar': 'ui/toolbar',
};
