export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './KbdToolbarButton';
export * from './kbdValue';
`;

export const indexFile = {
  '/kbd/index.ts': indexCode,
};
