export const DEFAULT_PLAYBACK_DELAY_IN_MS = 50;
export const DEFAULT_PLAYBACK_BURST_SIZE = 1;

export const playbackDelayOptions = [
  { label: '0 ms', value: 0 },
  { label: '10 ms', value: 10 },
  { label: '16 ms', value: 16 },
  { label: '25 ms', value: 25 },
  { label: '50 ms', value: 50 },
  { label: '100 ms', value: 100 },
  { label: '200 ms', value: 200 },
] as const;

export const playbackBurstSizeOptions = [
  { label: '1 chunk', value: 1 },
  { label: '2 chunks', value: 2 },
  { label: '5 chunks', value: 5 },
  { label: '10 chunks', value: 10 },
  { label: '25 chunks', value: 25 },
] as const;

type MarkdownStreamingDemoScenario = {
  chunks: readonly string[];
  label: string;
  syntax: 'markdown' | 'mdx';
};

function splitTextIntoChunks(
  source: string,
  pattern: readonly number[]
): string[] {
  const chunks: string[] = [];
  let index = 0;
  let patternIndex = 0;

  while (index < source.length) {
    const size = pattern[patternIndex % pattern.length]!;
    chunks.push(source.slice(index, index + size));
    index += size;
    patternIndex += 1;
  }

  return chunks;
}

const JITTERY_MARKDOWN_CHUNK_PATTERN = [1, 5, 2, 7, 3, 4, 1, 8, 2, 6] as const;
const JITTERY_MDX_CHUNK_PATTERN = [2, 1, 6, 3, 5, 1, 7, 2, 4, 8] as const;

export const liveMarkdownEditorsArticleChunks = [
  '#',
  ' Streaming',
  ' Markdown',
  ' Editors',
  ':',
  ' A',
  ' Modern',
  ' Approach',
  ' to',
  ' Real',
  '-Time',
  ' Writing',
  '\n\n',
  'Streaming',
  ' Markdown',
  ' editors',
  ' are',
  ' revolution',
  'izing',
  ' the',
  ' way',
  ' writers',
  ' and',
  ' developers',
  ' create',
  ' content',
  '.',
  ' They',
  ' enable',
  ' real',
  '-time',
  ' preview',
  ',',
  ' collaboration',
  ',',
  ' and',
  ' seamless',
  ' integration',
  ' with',
  ' other',
  ' tools',
  ',',
  ' making',
  ' the',
  ' writing',
  ' process',
  ' more',
  ' efficient',
  ' and',
  ' enjoyable',
  '.\n\n',
  '##',
  ' Features',
  ' of',
  ' Streaming',
  ' Markdown',
  ' Editors',
  '\n\n',
  '-',
  ' **',
  'Real',
  '-time',
  ' Preview',
  ':**',
  ' See',
  ' the',
  ' formatted',
  ' output',
  ' as',
  ' you',
  ' type',
  ',',
  ' without',
  ' needing',
  ' to',
  ' refresh',
  '.\n',
  '-',
  ' **',
  'Coll',
  'aboration',
  ':**',
  ' Multiple',
  ' users',
  ' can',
  ' edit',
  ' the',
  ' same',
  ' document',
  ' simultaneously',
  '.\n',
  '-',
  ' **',
  'Syntax',
  ' Highlight',
  'ing',
  ':**',
  ' Enh',
  'ances',
  ' readability',
  ' of',
  ' Markdown',
  ' code',
  '.\n',
  '-',
  ' **',
  'Export',
  ' Options',
  ':**',
  ' Easily',
  ' convert',
  ' Markdown',
  ' to',
  ' HTML',
  ',',
  ' PDF',
  ',',
  ' or',
  ' other',
  ' formats',
  '.\n',
  '-',
  ' **',
  'Version',
  ' Control',
  ':**',
  ' Keep',
  ' track',
  ' of',
  ' changes',
  ' and',
  ' revert',
  ' to',
  ' previous',
  ' versions',
  '.\n',
  '-',
  ' **',
  'Cloud',
  ' Sync',
  'ing',
  ':**',
  ' Save',
  ' your',
  ' work',
  ' automatically',
  ' in',
  ' the',
  ' cloud',
  '.\n\n',
  '##',
  ' Popular',
  ' Streaming',
  ' Markdown',
  ' Editors',
  ' Comparison',
  '\n\n',
  '|',
  ' Editor',
  '         ',
  ' |',
  ' Real',
  '-time',
  ' Preview',
  ' |',
  ' Collaboration',
  ' |',
  ' Export',
  ' Formats',
  '          ',
  ' |',
  ' Platform',
  '         ',
  ' |\n',
  '|',
  '----------------',
  '-|',
  '----------------',
  '---',
  '|',
  '---------------',
  '|',
  '----------------',
  '----------',
  '|',
  '----------------',
  '---',
  '|\n',
  '|',
  ' Typ',
  'ora',
  '         ',
  ' |',
  ' Yes',
  '              ',
  ' |',
  ' No',
  '           ',
  ' |',
  ' HTML',
  ',',
  ' PDF',
  ',',
  ' DOC',
  'X',
  '         ',
  ' |',
  ' Windows',
  ',',
  ' Mac',
  ',',
  ' Linux',
  '|\n',
  '|',
  ' Hack',
  'MD',
  '         ',
  ' |',
  ' Yes',
  '              ',
  ' |',
  ' Yes',
  '          ',
  ' |',
  ' HTML',
  ',',
  ' PDF',
  ',',
  ' Slide',
  ' Deck',
  's',
  '  ',
  ' |',
  ' Web',
  '-based',
  '        ',
  ' |\n',
  '|',
  ' Mark',
  ' Text',
  '      ',
  ' |',
  ' Yes',
  '              ',
  ' |',
  ' No',
  '           ',
  ' |',
  ' HTML',
  ',',
  ' PDF',
  '               ',
  ' |',
  ' Windows',
  ',',
  ' Mac',
  ',',
  ' Linux',
  '|\n',
  '|',
  ' Stack',
  'Edit',
  '      ',
  ' |',
  ' Yes',
  '              ',
  ' |',
  ' Yes',
  '          ',
  ' |',
  ' HTML',
  ',',
  ' PDF',
  ',',
  ' Google',
  ' Docs',
  '  ',
  ' |',
  ' Web',
  '-based',
  '        ',
  ' |\n\n',
  '>',
  ' "',
  'A',
  ' streaming',
  ' markdown',
  ' editor',
  ' brings',
  ' the',
  ' power',
  ' of',
  ' real',
  '-time',
  ' collaboration',
  ' to',
  ' the',
  ' simplicity',
  ' of',
  ' Markdown',
  '."',
  ' –',
  ' Tech',
  ' Writing',
  ' Daily',
  '\n\n',
  '##',
  ' Try',
  ' a',
  ' Streaming',
  ' Markdown',
  ' Editor',
  '\n\n',
  'Explore',
  ' **',
  '[',
  'Hack',
  'MD',
  '](',
  'https',
  '://',
  'hack',
  'md',
  '.io',
  '/',
  ')**',
  ',',
  ' a',
  ' popular',
  ' web',
  '-based',
  ' streaming',
  ' markdown',
  ' editor',
  ',',
  ' to',
  ' experience',
  ' collaborative',
  ' writing',
  ' and',
  ' seamless',
  ' preview',
  ' features',
  '.\n\n',
  '##',
  ' Sample',
  ' Markdown',
  ' Code',
  '\n\n',
  '```',
  'markdown',
  '\n',
  '#',
  ' Sample',
  ' Document',
  '\n\n',
  '-',
  ' Write',
  ' your',
  ' Markdown',
  ' content',
  ' here',
  '\n',
  '-',
  ' Preview',
  ' updates',
  ' automatically',
  '\n',
  '-',
  ' Collabor',
  'ate',
  ' with',
  ' others',
  ' live',
  '\n\n',
  '**',
  'Happy',
  ' writing',
  '!',
  '**\n',
  '``',
  '`\n',
] as const;

const markdownDenseMixedContentChunks = splitTextIntoChunks(
  [
    '# Dense markdown stream',
    '',
    '> Streaming markdown should keep quotes, tables, and code fences stable.',
    '',
    '1. Ordered item',
    '2. Ordered item with nested bullets',
    '   - nested bullet',
    '   - [x] finished task',
    '3. Final item',
    '',
    '---',
    '',
    '| Surface | Status |',
    '| --- | --- |',
    '| Toolbar | steady |',
    '| Selection | tracked |',
    '',
    '```ts',
    'export function greet(name: string) {',
    '  return "hi " + name;',
    '}',
    '```',
    '',
    'See [Plate](https://platejs.org) and ![Preview](https://placehold.co/120x80).',
  ].join('\n'),
  JITTERY_MARKDOWN_CHUNK_PATTERN
);

const markdownHtmlDetailsChunks = splitTextIntoChunks(
  [
    '## Markdown with raw HTML',
    '',
    'Paragraph with `inline code`, **bold**, and ~~cleanup~~.',
    '',
    '<details>',
    '<summary>Expandable note</summary>',
    '',
    'Raw HTML inside markdown should stay grouped while the stream advances.',
    '',
    '</details>',
    '',
    '- [Docs](https://platejs.org/docs)',
    '- <kbd>Cmd</kbd> + <kbd>K</kbd>',
  ].join('\n'),
  [3, 1, 5, 2, 6, 1, 4, 7, 2] as const
);

const mdxCalloutAndStepsChunks = splitTextIntoChunks(
  [
    '## MDX walkthrough',
    '',
    '<column_group layout="[50,50]">',
    '<column width="50%">',
    '',
    '### Install Plate',
    '',
    'Run `pnpm install` and open the demo route.',
    '',
    '</column>',
    '',
    '<column width="50%">',
    '',
    '### Stream chunks',
    '',
    'Replay the preset to inspect the editor tree.',
    '',
    '</column>',
    '</column_group>',
    '',
    '<callout type="note">',
    '  This preset mixes markdown headings with supported MDX block components.',
    '</callout>',
  ].join('\n'),
  JITTERY_MDX_CHUNK_PATTERN
);

const mdxImportExportAndCalloutChunks = splitTextIntoChunks(
  [
    '# MDX callout props',
    '',
    '<callout type="info" title="Chunky props" icon="ℹ️">',
    '  Attributes on supported MDX nodes should survive awkward chunk boundaries.',
    '</callout>',
    '',
    '<column_group layout="[60,40]">',
    '<column width="60%">',
    '',
    '- Keep the editor alive',
    '- Keep the markdown readable',
    '</column>',
    '',
    '<column width="40%">',
    '',
    '### Inspect',
    '',
    'Watch the editor tree update.',
    '</column>',
    '</column_group>',
  ].join('\n'),
  [1, 4, 2, 6, 3, 1, 8, 2, 5, 7] as const
);

const mdxFenceAndChecklistChunks = splitTextIntoChunks(
  [
    '# MDX with fenced code',
    '',
    '<callout type="warning" title="Edge boundary">',
    '  Streaming code fences after MDX tags should still parse.',
    '</callout>',
    '',
    '```tsx',
    'export function Demo() {',
    '  return <div data-mode="streaming">ready</div>;',
    '}',
    '```',
    '',
    '- [x] Preserve the fence',
    '- [ ] Preserve the trailing list',
  ].join('\n'),
  [2, 5, 1, 7, 3, 2, 6, 1, 4, 8] as const
);

const mdxInlineTagsAndTrailingCalloutChunks = splitTextIntoChunks(
  [
    '## MDX inline tags',
    '',
    'Inline <comment>commented</comment>, <suggestion>suggested</suggestion>, <date>2026-04-01</date>, <kbd>Cmd</kbd> + <kbd>K</kbd>, <mark>highlight</mark>, <u>underline</u>, H<sub>low</sub>O, x<sup>high</sup>, and <span style="font-weight: 700; color: tomato;">styled</span> text should stay visible.',
    '',
    '<callout type="success" title="Trailing flow tag">',
    '  A supported flow tag should still parse after a long inline MDX run.',
    '</callout>',
  ].join('\n'),
  [1, 3, 2, 5, 1, 4, 6, 2, 7, 3] as const
);

const mdxMediaAndTocRelayChunks = splitTextIntoChunks(
  [
    '# MDX media relay',
    '',
    '<file src="https://example.com/spec.pdf" name="spec.pdf"></file>',
    '',
    '<audio src="https://example.com/clip.mp3"></audio>',
    '',
    '<video src="https://example.com/demo.mp4" width="80%" align="center"></video>',
    '',
    '<toc></toc>',
    '',
    '<callout type="info" title="After media">',
    '  A new supported flow tag should still parse after media and toc tags.',
    '</callout>',
  ].join('\n'),
  [2, 6, 1, 5, 3, 7, 2, 4, 1, 8] as const
);

const mdxFlowRelayWithTrailingTagsChunks = splitTextIntoChunks(
  [
    '# MDX flow relay',
    '',
    '<callout type="warning" title="Flow one">',
    '  The next supported tag starts right after this block.',
    '</callout>',
    '',
    '<column_group layout="[70,30]" count="2">',
    '<column width="70%" sticky="true">',
    '',
    '- Primary lane',
    '- Nested markdown still streams',
    '</column>',
    '',
    '<column width="30%">',
    '',
    '<toc></toc>',
    '</column>',
    '</column_group>',
    '',
    '<callout type="success" title="Flow two">',
    '  Another supported tag follows the completed columns.',
    '</callout>',
  ].join('\n'),
  [3, 1, 7, 2, 5, 1, 8, 2, 4, 6] as const
);

const columnsChunks = [
  'paragraph\n\n<column',
  '_group',
  '>\n',
  ' ',
  ' <',
  'column',
  ' width',
  '="',
  '33',
  '.',
  '333',
  '333',
  '333',
  '333',
  '336',
  '%">\n',
  '   ',
  ' ',
  '1',
  '\n',
  ' ',
  ' </',
  'column',
  '>\n',
  ' ',
  ' <',
  'column',
  ' width',
  '="',
  '33',
  '.',
  '333',
  '333',
  '333',
  '333',
  '336',
  '%">\n',
  '   ',
  ' ',
  '2',
  '\n',
  ' ',
  ' </',
  'column',
  '>\n',
  ' ',
  ' <',
  'column',
  ' width',
  '="',
  '33',
  '.',
  '333',
  '333',
  '333',
  '333',
  '336',
  '%">\n',
  '   ',
  ' ',
  '3',
  '\n',
  ' ',
  ' </',
  'column',
  '>\n',
  '</',
  'column',
  '_group',
  '>\n\nparagraph',
] as const;

const linksChunks = [
  '[Link ',
  'to OpenA',
  'I](https://www.openai.com)\n\n',
  '[Link ',
  'to Google',
  'I](https://ww',
  'w.google.com/1',
  '11',
  '22',
  'xx',
  'yy',
  'zz',
  'aa',
  'bb',
  'cc',
  'dd',
  'ee',
  '33)\n\n',
  '[False Positive',
  '11',
  '22',
  '33',
  '44',
  '55',
  '66',
  '77',
  '88',
  '99',
  '100',
] as const;

const listsChunks = [
  '1.',
  ' number 1\n',
  '- ',
  'List B\n',
  '-',
  ' [x] ',
  'Task C',
] as const;

const listWithImageChunks = [
  '## ',
  'Links ',
  'and ',
  'Images\n\n',
  '- [Link ',
  'to OpenA',
  'I](https://www.openai.com)\n',
  '- ![Sample Image](https://via.placeholder.com/150)\n\n',
] as const;

const nestedStructureBlockChunks = [
  '```',
  'javascript',
  '\n',
  'import',
  ' React',
  ' from',
  " '",
  'react',
  "';\n",
  'import',
  ' {',
  ' Plate',
  ' }',
  ' from',
  " '@",
  'ud',
  'ecode',
  '/',
  'plate',
  "';\n\n",
  'const',
  ' Basic',
  'Editor',
  ' =',
  ' ()',
  ' =>',
  ' {\n',
  ' ',
  ' return',
  ' (\n',
  '   ',
  ' <',
  'Plate',
  '>\n',
  '     ',
  ' {/*',
  ' Add',
  ' your',
  ' plugins',
  ' and',
  ' components',
  ' here',
  ' */}\n',
  '   ',
  ' </',
  'Plate',
  '>\n',
  ' ',
  ' );\n',
  '};\n\n',
  'export',
  ' default',
  ' Basic',
  'Editor',
  ';\n',
  '```',
] as const;

const tableChunks = [
  '| Feature          |',
  ' Plate',
  '.js',
  '                                     ',
  ' ',
  '| Slate.js                                     ',
  ' ',
  '|\n|------------------',
  '|--------------------------------',
  '---------------',
  '|--------------------------------',
  '---------------',
  '|\n| Purpose         ',
  ' ',
  '| Rich text editor framework',
  '                   ',
  ' ',
  '| Rich text editor framework',
  '                   ',
  ' ',
  '|\n| Flexibility     ',
  ' ',
  '| Highly customizable',
  ' with',
  ' plugins',
  '             ',
  ' ',
  '| Highly customizable',
  ' with',
  ' plugins',
  '             ',
  ' ',
  '|\n| Community       ',
  ' ',
  '| Growing community support',
  '                    ',
  ' ',
  '| Established community',
  ' support',
  '                ',
  ' ',
  '|\n| Documentation   ',
  ' ',
  '| Comprehensive documentation',
  ' available',
  '        ',
  ' ',
  '| Comprehensive documentation',
  ' available',
  '        ',
  ' ',
  '|\n| Performance     ',
  ' ',
  '| Optimized for performance',
  ' with',
  ' large',
  ' documents',
  '| Good performance, but',
  ' may',
  ' require',
  ' optimization',
  '|\n| Integration     ',
  ' ',
  '| Easy integration with',
  ' React',
  '                  ',
  ' ',
  '| Easy integration with',
  ' React',
  '                  ',
  ' ',
  '|\n| Use Cases       ',
  ' ',
  '| Suitable for complex',
  ' editing',
  ' needs',
  '           ',
  ' ',
  '| Suitable for complex',
  ' editing',
  ' needs',
  '           ',
  ' ',
  '\n\n',
  'Paragraph ',
  'should ',
  'exist ',
  'from ',
  'table',
] as const;

const highlightErrorReproChunks = [
  '#',
  ' Sample',
  ' Markdown',
  ' Document',
  '\n\n',
  '##',
  ' Title',
  ':',
  ' Understanding',
  ' Markdown',
  '\n\n',
  'Markdown',
  ' is',
  ' a',
  ' lightweight',
  ' markup',
  ' language',
  ' that',
  ' allows',
  ' you',
  ' to',
  ' format',
  ' text',
  ' using',
  ' plain',
  ' text',
  ' syntax',
  '.\n\n',
  '###',
  ' Key',
  ' Features',
  ' of',
  ' Markdown',
  '\n\n',
  '- *',
  '*Headers**: Use `#` for headers',
  '.',
  ' More',
  ' ',
  '`#` symbols indicate smaller headers',
  '.\n',
  '- *',
  '*Lists**:\n',
  ' ',
  ' ',
  '- Bullet',
  ' points',
  ' can',
  ' be',
  ' created',
  ' using',
  ' ',
  '`-`, `*`, or `+`.\n',
  ' ',
  ' ',
  '- Number',
  'ed',
  ' lists',
  ' use',
  ' numbers',
  ' followed',
  ' by',
  ' a',
  ' period',
  '.\n\n',
  '###',
  ' Example',
  ' of',
  ' a',
  ' Code',
  ' Block',
  '\n\n',
  '```python\n',
  'def hello_world():\n',
  '    print("Hello, World!")\n',
  '```\n\n',
  '###',
  ' Links',
  ' and',
  ' Images',
  '\n\n',
  '- [Visit OpenAI](https://www.open',
  'ai',
  '.com',
  ')\n',
  '- !',
  '[Markdown Logo](https://markdown-here.com/img/icon256.png)\n\n',
  '###',
  ' Conclusion',
  '\n\n',
  'Using',
  ' Markdown',
  ' makes',
  ' it',
  ' easy',
  ' to',
  ' write',
  ' and',
  ' format',
  ' text',
  ' for',
  ' various',
  ' applications',
  '.',
] as const;

export const markdownStreamingDemoFixtureSections = {
  columns: columnsChunks,
  highlightErrorRepro: highlightErrorReproChunks,
  links: linksChunks,
  listWithImage: listWithImageChunks,
  lists: listsChunks,
  liveMarkdownEditorsArticle: liveMarkdownEditorsArticleChunks,
  markdownDenseMixedContent: markdownDenseMixedContentChunks,
  markdownHtmlDetails: markdownHtmlDetailsChunks,
  mdxCalloutAndColumns: mdxCalloutAndStepsChunks,
  mdxCalloutPropsAndColumns: mdxImportExportAndCalloutChunks,
  mdxFenceAndChecklist: mdxFenceAndChecklistChunks,
  mdxFlowRelayWithTrailingTags: mdxFlowRelayWithTrailingTagsChunks,
  mdxInlineTagsAndTrailingCallout: mdxInlineTagsAndTrailingCalloutChunks,
  mdxMediaAndTocRelay: mdxMediaAndTocRelayChunks,
  nestedStructureBlock: nestedStructureBlockChunks,
  table: tableChunks,
} as const;

const mergedMarkdownStreamingScenarioChunks = splitTextIntoChunks(
  [
    '# All scenarios combined',
    '',
    '<callout type="warning" title="Chunky props" icon="ℹ️">',
    'Keep the editor alive.',
    'Streaming code fences after MDX tags should still parse.',
    '</callout>',
    '',
    'Inline <comment>commented</comment>, <suggestion>suggested</suggestion>, <date>2026-04-01</date>, <kbd>Cmd</kbd> + <kbd>K</kbd>, <mark>highlight</mark>, <u>underline</u>, H<sub>low</sub>O, x<sup>high</sup>, and <span style="font-weight: 700; color: tomato;">styled</span> text should stay visible.',
    '',
    '<column_group layout="[70,30]" count="2">',
    '<column width="70%" sticky="true">',
    '',
    '- Primary lane',
    '- Nested markdown still streams',
    '',
    '</column>',
    '<column width="30%">',
    '',
    '<toc></toc>',
    '',
    '</column>',
    '</column_group>',
    '',
    '<file src="https://example.com/spec.pdf" name="spec.pdf"></file>',
    '',
    '<audio src="https://example.com/clip.mp3"></audio>',
    '',
    '<video src="https://example.com/demo.mp4" width="80%" align="center"></video>',
    '',
    '## Markdown basics',
    '',
    '- [Visit OpenAI](https://www.openai.com)',
    '- ![Markdown Logo](https://markdown-here.com/img/icon256.png)',
    '1. number 1',
    '- List B',
    '- [x] Task C',
    '',
    '```python',
    'def hello_world():',
    '    print("Hello, World!")',
    '```',
    '',
    '| Editor | Output |',
    '| --- | --- |',
    '| Plate | steady |',
    '| Typora | preview |',
    '',
    'Paragraph should exist from table',
  ].join('\n'),
  JITTERY_MDX_CHUNK_PATTERN
);

export const markdownStreamingDemoScenarios = {
  allScenariosCombined: {
    chunks: mergedMarkdownStreamingScenarioChunks,
    label: 'All Scenarios Combined',
    syntax: 'mdx',
  },
} as const satisfies Record<string, MarkdownStreamingDemoScenario>;

export type MarkdownStreamingDemoScenarioId =
  keyof typeof markdownStreamingDemoScenarios;

export const DEFAULT_MARKDOWN_STREAMING_DEMO_SCENARIO_ID =
  'allScenariosCombined' satisfies MarkdownStreamingDemoScenarioId;

export function getPlaybackDelayInMs(
  playbackDelayInMs: number,
  chunkDelayInMs?: number | null
) {
  return Math.max(playbackDelayInMs, chunkDelayInMs ?? 0);
}

export function getNextPlaybackIndex(
  currentIndex: number,
  totalChunks: number,
  playbackBurstSize: number
) {
  return Math.min(totalChunks, currentIndex + playbackBurstSize);
}
