export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './IFrame';
export * from './iframeValue';
`;

export const indexFile = {
  '/iframe/index.ts': indexCode,
};
