export {
  applyStringDiff,
  CAN_USE_DOM,
  type DOMElement,
  type DOMNode,
  type DOMPoint,
  type DOMRange,
  type DOMSelection,
  type DOMStaticRange,
  type DOMText,
  getActiveElement,
  getDefaultView,
  getSelection,
  HAS_BEFORE_INPUT_SUPPORT,
  hasShadowRoot,
  IS_ANDROID,
  IS_CHROME,
  IS_FIREFOX,
  IS_FIREFOX_LEGACY,
  IS_IOS,
  IS_UC_MOBILE,
  IS_WEBKIT,
  IS_WECHATBROWSER,
  isAfter,
  isBefore,
  isDOMElement,
  isDOMNode,
  isDOMSelection,
  isElementDecorationsEqual,
  isPlainTextOnlyPaste,
  isTextDecorationsEqual,
  isTrackedMutation,
  mergeStringDiffs,
  normalizeDOMPoint,
  normalizePoint,
  normalizeRange,
  normalizeStringDiff,
  type StringDiff,
  type TextDiff,
  TRIPLE_CLICK,
  targetRange,
  verifyDiffState,
  withDOM,
} from 'slate-dom';
