export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './imagePlugins';
export * from './imageValue';
`;

export const indexFile = {
  '/image/index.ts': indexCode,
};
