export declare const MISSING_DIR_OR_EMPTY_PROJECT = "1";
export declare const EXISTING_CONFIG = "2";
export declare const MISSING_CONFIG = "3";
export declare const MISSING_REGISTRY = "3b";
export declare const FAILED_CONFIG_READ = "4";
export declare const TAILWIND_NOT_CONFIGURED = "5";
export declare const IMPORT_ALIAS_MISSING = "6";
export declare const UNSUPPORTED_FRAMEWORK = "7";
export declare const COMPONENT_URL_NOT_FOUND = "8";
export declare const COMPONENT_URL_UNAUTHORIZED = "9";
export declare const COMPONENT_URL_FORBIDDEN = "10";
export declare const COMPONENT_URL_BAD_REQUEST = "11";
export declare const COMPONENT_URL_INTERNAL_SERVER_ERROR = "12";
//# sourceMappingURL=errors.d.ts.map