import { createPlatePackageConfig } from '../../tooling/config/tsdown.config.ts';

export default createPlatePackageConfig({
  additionalEntries: [
    'src/ai/index.ts',
    'src/ai/react/index.ts',
    'src/features/callout/index.ts',
    'src/features/combobox/index.ts',
    'src/features/comment/index.ts',
    'src/features/date/index.ts',
    'src/features/details/index.ts',
    'src/features/footnote/index.ts',
    'src/features/layout/index.ts',
    'src/features/media/index.ts',
    'src/features/mention/index.ts',
    'src/features/slash-command/index.ts',
    'src/features/suggestion/index.ts',
    'src/features/table/index.ts',
    'src/features/tag/index.ts',
    'src/features/toc/index.ts',
    'src/react/features/callout/index.ts',
    'src/react/features/comment/index.ts',
    'src/react/features/date/index.ts',
    'src/react/features/details/index.ts',
    'src/react/features/footnote/index.ts',
    'src/react/features/layout/index.ts',
    'src/react/features/media/index.ts',
    'src/react/features/mention/index.ts',
    'src/react/features/resizable/index.ts',
    'src/react/features/slash-command/index.ts',
    'src/react/features/suggestion/index.ts',
    'src/react/features/table/index.ts',
    'src/react/features/tag/index.ts',
    'src/react/features/toc/index.ts',
    'src/code-drawing/index.ts',
    'src/code-drawing/react/index.ts',
    'src/csv/index.ts',
    'src/diff/index.ts',
    'src/dnd/react/index.ts',
    'src/docx/index.ts',
    'src/dom/index.ts',
    'src/emoji/index.ts',
    'src/emoji/react/index.ts',
    'src/excalidraw/index.ts',
    'src/excalidraw/react/index.ts',
    'src/history/index.ts',
    'src/hyperscript/index.ts',
    'src/juice/index.ts',
    'src/markdown/index.ts',
    'src/math/index.ts',
    'src/math/react/index.ts',
    'src/migrations/index.ts',
    'src/pagination/index.ts',
    'src/pagination/react/index.ts',
    'src/tabbable/index.ts',
    'src/tabbable/react/index.ts',
    'src/testing/index.ts',
    'src/yjs/index.ts',
    'src/yjs/react/index.ts',
  ],
  directDeclarations: false,
  unbundle: true,
});
