export {
  domCommands,
  createCompiledHotkeyMatcher,
  dom,
  DOMEditor,
  getEditorDOMRoot,
  getSelection,
  dataTransferFormats,
  isGeckoDOMHost,
  isHotkey,
  usesAppleDOMHotkeys,
  writeDOMFragmentData,
} from 'plitejs/dom';

export type {
  DOMApi,
  DOMClipboardApi,
  DOMElement,
  DOMPlugin,
  DOMNode,
  DOMRange,
  DOMText,
  DataTransferFormat,
  DataTransferDecodeResult,
  DataTransferDecodeContext,
  DataTransferEncodeResult,
  DataTransferReport,
  DataTransferSchemaClaim,
  DataTransferEncodeContext,
  DataTransferSnapshot,
  HotkeySpec,
  KeyboardEventLike,
  ScrollIntoViewOptions,
} from 'plitejs/dom';
