export {
  clipboardHandler,
  createCompiledHotkeyMatcher,
  dom,
  DOMEditor,
  getEditorDOMRoot,
  getSelection,
  hostCodecs,
  isGeckoDOMHost,
  isHotkey,
  parseDOMClipboardHtml,
  usesAppleDOMHotkeys,
  writeDOMFragmentData,
} from 'plitejs/dom';

export type {
  DOMApi,
  DOMClipboardApi,
  DOMElement,
  DOMExtension,
  DOMNode,
  DOMRange,
  DOMText,
  HostCodec,
  HostCodecParseContext,
  HostCodecSchemaTarget,
  HostCodecSerializeContext,
  HotkeySpec,
  KeyboardEventLike,
  ScrollIntoViewOptions,
} from 'plitejs/dom';
