export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './forcedLayoutPlugin';
export * from './forcedLayoutValue';
`;

export const indexFile = {
  '/forced-layout/index.ts': indexCode,
};
