/**
 * @file Automatically generated by barrelsby.
 */

export * from './search-highlight/SearchHighlightPlugin';
export * from './search-highlight/defaults';
export * from './search-highlight/types';
export * from './search-highlight/useDecorateSearchHighlight';
