export {
  authored,
  authoredProjectionDiagnostics,
  isAuthoredEditor,
  createAuthoredImportedRevisionChange,
  createAuthoredReviewDocument,
  parseAuthoredDocument,
  projectAuthoredRange,
  projectAuthoredDocument,
  projectAuthoredReview,
  proposeAuthoredComparison,
  type AuthoredChange,
  type AuthoredEditor,
  type AuthoredChangePublication,
  type AuthoredComparisonImportResult,
  type AuthoredChangeContent,
  type AuthoredChangeDetails,
  type AuthoredChangeKind,
  type AuthoredChangeLocation,
  type AuthoredChangePart,
  type AuthoredChangeReview,
  type AuthoredDecision,
  type AuthoredPlugin,
  type AuthoredDocumentProjection,
  type AuthoredFormatProjection,
  type AuthoredFormatPropertyChange,
  type AuthoredFormatSegment,
  type AuthoredImportedRevision,
  type AuthoredImportedRevisionSection,
  type AuthoredProjectionDiagnostic,
  type AuthoredReviewProjection,
  type AuthoredUnresolvedChangeCounts,
  type AuthoredOptions,
  type AuthoredPage,
  type AuthoredQuery,
  type AuthoredResult,
  type AuthoredSelection,
  type AuthoredStatus,
  type AuthoredView,
} from 'plitejs/authored';
export * from './PlateAuthoredPlugin';
