import { MentionNodeData } from '@udecode/slate-plugins';

export const MENTIONABLES: MentionNodeData[] = [
  { value: "0", name: "Aayla Secura", email: "aayla_secura@force.com" },
  { value: "1", name: "Adi Gallia", email: "adi_gallia@force.com" },
  {
    value: "2",
    name: "Admiral Dodd Rancit",
    email: "admiral_dodd_rancit@force.com",
  },
  {
    value: "3",
    name: "Admiral Firmus Piett",
    email: "admiral_firmus_piett@force.com",
  },
  {
    value: "4",
    name: "Admiral Gial Ackbar",
    email: "admiral_gial_ackbar@force.com",
  },
  { value: "5", name: "Admiral Ozzel", email: "admiral_ozzel@force.com" },
  { value: "6", name: "Admiral Raddus", email: "admiral_raddus@force.com" },
  {
    value: "7",
    name: "Admiral Terrinald Screed",
    email: "admiral_terrinald_screed@force.com",
  },
  { value: "8", name: "Admiral Trench", email: "admiral_trench@force.com" },
  {
    value: "9",
    name: "Admiral U.O. Statura",
    email: "admiral_u.o._statura@force.com",
  },
  { value: "10", name: "Agen Kolar", email: "agen_kolar@force.com" },
  { value: "11", name: "Agent Kallus", email: "agent_kallus@force.com" },
  {
    value: "12",
    name: "Aiolin and Morit Astarte",
    email: "aiolin_and_morit_astarte@force.com",
  },
  { value: "13", name: "Aks Moe", email: "aks_moe@force.com" },
  { value: "14", name: "Almec", email: "almec@force.com" },
  { value: "15", name: "Alton Kastle", email: "alton_kastle@force.com" },
  { value: "16", name: "Amee", email: "amee@force.com" },
  { value: "17", name: "AP-5", email: "ap-5@force.com" },
  { value: "18", name: "Armitage Hux", email: "armitage_hux@force.com" },
  { value: "19", name: "Artoo", email: "artoo@force.com" },
  { value: "20", name: "Arvel Crynyd", email: "arvel_crynyd@force.com" },
  { value: "21", name: "Asajj Ventress", email: "asajj_ventress@force.com" },
  { value: "22", name: "Aurra Sing", email: "aurra_sing@force.com" },
  { value: "23", name: "AZI-3", email: "azi-3@force.com" },
  { value: "24", name: "Bala-Tik", email: "bala-tik@force.com" },
  { value: "25", name: "Barada", email: "barada@force.com" },
  { value: "26", name: "Bargwill Tomder", email: "bargwill_tomder@force.com" },
  { value: "27", name: "Baron Papanoida", email: "baron_papanoida@force.com" },
  { value: "28", name: "Barriss Offee", email: "barriss_offee@force.com" },
  { value: "29", name: "Baze Malbus", email: "baze_malbus@force.com" },
  { value: "30", name: "Bazine Netal", email: "bazine_netal@force.com" },
  { value: "31", name: "BB-8", email: "bb-8@force.com" },
  { value: "32", name: "BB-9E", email: "bb-9e@force.com" },
  { value: "33", name: "Ben Quadinaros", email: "ben_quadinaros@force.com" },
  { value: "34", name: "Berch Teller", email: "berch_teller@force.com" },
  { value: "35", name: "Beru Lars", email: "beru_lars@force.com" },
  { value: "36", name: "Bib Fortuna", email: "bib_fortuna@force.com" },
  {
    value: "37",
    name: "Biggs Darklighter",
    email: "biggs_darklighter@force.com",
  },
  { value: "38", name: "Black Krrsantan", email: "black_krrsantan@force.com" },
  { value: "39", name: "Bo-Katan Kryze", email: "bo-katan_kryze@force.com" },
  { value: "40", name: "Boba Fett", email: "boba_fett@force.com" },
  { value: "41", name: "Bobbajo", email: "bobbajo@force.com" },
  { value: "42", name: "Bodhi Rook", email: "bodhi_rook@force.com" },
  { value: "43", name: "Borvo the Hutt", email: "borvo_the_hutt@force.com" },
  { value: "44", name: "Boss Nass", email: "boss_nass@force.com" },
  { value: "45", name: "Bossk", email: "bossk@force.com" },
  {
    value: "46",
    name: "Breha Antilles-Organa",
    email: "breha_antilles-organa@force.com",
  },
  { value: "47", name: "Bren Derlin", email: "bren_derlin@force.com" },
  { value: "48", name: "Brendol Hux", email: "brendol_hux@force.com" },
  { value: "49", name: "BT-1", email: "bt-1@force.com" },
  { value: "50", name: "C-3PO", email: "c-3po@force.com" },
  { value: "51", name: "C1-10P", email: "c1-10p@force.com" },
  { value: "52", name: "Cad Bane", email: "cad_bane@force.com" },
  { value: "53", name: "Caluan Ematt", email: "caluan_ematt@force.com" },
  { value: "54", name: "Captain Gregor", email: "captain_gregor@force.com" },
  { value: "55", name: "Captain Phasma", email: "captain_phasma@force.com" },
  {
    value: "56",
    name: "Captain Quarsh Panaka",
    email: "captain_quarsh_panaka@force.com",
  },
  { value: "57", name: "Captain Rex", email: "captain_rex@force.com" },
  { value: "58", name: "Carlist Rieekan", email: "carlist_rieekan@force.com" },
  { value: "59", name: "Casca Panzoro", email: "casca_panzoro@force.com" },
  { value: "60", name: "Cassian Andor", email: "cassian_andor@force.com" },
  { value: "61", name: "Cassio Tagge", email: "cassio_tagge@force.com" },
  { value: "62", name: "Cham Syndulla", email: "cham_syndulla@force.com" },
  {
    value: "63",
    name: "Che Amanwe Papanoida",
    email: "che_amanwe_papanoida@force.com",
  },
  { value: "64", name: "Chewbacca", email: "chewbacca@force.com" },
  {
    value: "65",
    name: "Chi Eekway Papanoida",
    email: "chi_eekway_papanoida@force.com",
  },
  { value: "66", name: "Chief Chirpa", email: "chief_chirpa@force.com" },
  { value: "67", name: "Chirrut Îmwe", email: "chirrut_îmwe@force.com" },
  { value: "68", name: "Ciena Ree", email: "ciena_ree@force.com" },
  { value: "69", name: "Cin Drallig", email: "cin_drallig@force.com" },
  { value: "70", name: "Clegg Holdfast", email: "clegg_holdfast@force.com" },
  { value: "71", name: "Cliegg Lars", email: "cliegg_lars@force.com" },
  { value: "72", name: "Coleman Kcaj", email: "coleman_kcaj@force.com" },
  { value: "73", name: "Coleman Trebor", email: "coleman_trebor@force.com" },
  { value: "74", name: "Colonel Kaplan", email: "colonel_kaplan@force.com" },
  { value: "75", name: "Commander Bly", email: "commander_bly@force.com" },
  {
    value: "76",
    name: "Commander Cody (CC-2224)",
    email: "commander_cody_(cc-2224)@force.com",
  },
  {
    value: "77",
    name: "Commander Fil (CC-3714)",
    email: "commander_fil_(cc-3714)@force.com",
  },
  { value: "78", name: "Commander Fox", email: "commander_fox@force.com" },
  { value: "79", name: "Commander Gree", email: "commander_gree@force.com" },
  { value: "80", name: "Commander Jet", email: "commander_jet@force.com" },
  {
    value: "81",
    name: "Commander Wolffe",
    email: "commander_wolffe@force.com",
  },
  {
    value: "82",
    name: "Conan Antonio Motti",
    email: "conan_antonio_motti@force.com",
  },
  { value: "83", name: "Conder Kyl", email: "conder_kyl@force.com" },
  { value: "84", name: "Constable Zuvio", email: "constable_zuvio@force.com" },
  { value: "85", name: "Cordé", email: "cordé@force.com" },
  { value: "86", name: "Cpatain Typho", email: "cpatain_typho@force.com" },
  { value: "87", name: "Crix Madine", email: "crix_madine@force.com" },
  { value: "88", name: "Cut Lawquane", email: "cut_lawquane@force.com" },
  { value: "89", name: "Dak Ralter", email: "dak_ralter@force.com" },
  { value: "90", name: "Dapp", email: "dapp@force.com" },
  { value: "91", name: "Darth Bane", email: "darth_bane@force.com" },
  { value: "92", name: "Darth Maul", email: "darth_maul@force.com" },
  { value: "93", name: "Darth Tyranus", email: "darth_tyranus@force.com" },
  { value: "94", name: "Daultay Dofine", email: "daultay_dofine@force.com" },
  { value: "95", name: "Del Meeko", email: "del_meeko@force.com" },
  { value: "96", name: "Delian Mors", email: "delian_mors@force.com" },
  { value: "97", name: "Dengar", email: "dengar@force.com" },
  { value: "98", name: "Depa Billaba", email: "depa_billaba@force.com" },
  { value: "99", name: "Derek Klivian", email: "derek_klivian@force.com" },
  { value: "100", name: "Dexter Jettster", email: "dexter_jettster@force.com" },
  { value: "101", name: "Dineé Ellberger", email: "dineé_ellberger@force.com" },
  { value: "102", name: "DJ", email: "dj@force.com" },
  { value: "103", name: "Doctor Aphra", email: "doctor_aphra@force.com" },
  { value: "104", name: "Doctor Evazan", email: "doctor_evazan@force.com" },
  { value: "105", name: "Dogma", email: "dogma@force.com" },
  { value: "106", name: "Dormé", email: "dormé@force.com" },
  { value: "107", name: "Dr. Cylo", email: "dr._cylo@force.com" },
  { value: "108", name: "Droidbait", email: "droidbait@force.com" },
  { value: "109", name: "Droopy McCool", email: "droopy_mccool@force.com" },
  { value: "110", name: "Dryden Vos", email: "dryden_vos@force.com" },
  { value: "111", name: "Dud Bolt", email: "dud_bolt@force.com" },
  { value: "112", name: "Ebe E. Endocott", email: "ebe_e._endocott@force.com" },
  { value: "113", name: "Echuu Shen-Jon", email: "echuu_shen-jon@force.com" },
  { value: "114", name: "Eeth Koth", email: "eeth_koth@force.com" },
  { value: "115", name: "Eighth Brother", email: "eighth_brother@force.com" },
  { value: "116", name: "Eirtaé", email: "eirtaé@force.com" },
  { value: "117", name: "Eli Vanto", email: "eli_vanto@force.com" },
  { value: "118", name: "Ellé", email: "ellé@force.com" },
  { value: "119", name: "Ello Asty", email: "ello_asty@force.com" },
  { value: "120", name: "Embo", email: "embo@force.com" },
  { value: "121", name: "Eneb Ray", email: "eneb_ray@force.com" },
  { value: "122", name: "Enfys Nest", email: "enfys_nest@force.com" },
  { value: "123", name: "EV-9D9", email: "ev-9d9@force.com" },
  { value: "124", name: "Evaan Verlaine", email: "evaan_verlaine@force.com" },
  { value: "125", name: "Even Piell", email: "even_piell@force.com" },
  { value: "126", name: "Ezra Bridger", email: "ezra_bridger@force.com" },
  { value: "127", name: "Faro Argyus", email: "faro_argyus@force.com" },
  { value: "128", name: "Feral", email: "feral@force.com" },
  { value: "129", name: "Fifth Brother", email: "fifth_brother@force.com" },
  { value: "130", name: "Finis Valorum", email: "finis_valorum@force.com" },
  { value: "131", name: "Finn", email: "finn@force.com" },
  { value: "132", name: "Fives", email: "fives@force.com" },
  { value: "133", name: "FN-1824", email: "fn-1824@force.com" },
  { value: "134", name: "FN-2003", email: "fn-2003@force.com" },
  {
    value: "135",
    name: "Fodesinbeed Annodue",
    email: "fodesinbeed_annodue@force.com",
  },
  { value: "136", name: "Fulcrum", email: "fulcrum@force.com" },
  { value: "137", name: "FX-7", email: "fx-7@force.com" },
  { value: "138", name: "GA-97", email: "ga-97@force.com" },
  { value: "139", name: "Galen Erso", email: "galen_erso@force.com" },
  { value: "140", name: "Gallius Rax", email: "gallius_rax@force.com" },
  {
    value: "141",
    name: 'Garazeb "Zeb" Orrelios',
    email: 'garazeb_"zeb"_orrelios@force.com',
  },
  {
    value: "142",
    name: "Gardulla the Hutt",
    email: "gardulla_the_hutt@force.com",
  },
  { value: "143", name: "Garrick Versio", email: "garrick_versio@force.com" },
  { value: "144", name: "Garven Dreis", email: "garven_dreis@force.com" },
  { value: "145", name: "Gavyn Sykes", email: "gavyn_sykes@force.com" },
  { value: "146", name: "Gideon Hask", email: "gideon_hask@force.com" },
  { value: "147", name: "Gizor Dellso", email: "gizor_dellso@force.com" },
  { value: "148", name: "Gonk droid", email: "gonk_droid@force.com" },
  {
    value: "149",
    name: "Grand Inquisitor",
    email: "grand_inquisitor@force.com",
  },
  {
    value: "150",
    name: "Greeata Jendowanian",
    email: "greeata_jendowanian@force.com",
  },
  { value: "151", name: "Greedo", email: "greedo@force.com" },
  { value: "152", name: "Greer Sonnel", email: "greer_sonnel@force.com" },
  { value: "153", name: "Grievous", email: "grievous@force.com" },
  { value: "154", name: "Grummgar", email: "grummgar@force.com" },
  { value: "155", name: "Gungi", email: "gungi@force.com" },
  { value: "156", name: "Hammerhead", email: "hammerhead@force.com" },
  { value: "157", name: "Han Solo", email: "han_solo@force.com" },
  { value: "158", name: "Harter Kalonia", email: "harter_kalonia@force.com" },
  { value: "159", name: "Has Obbit", email: "has_obbit@force.com" },
  { value: "160", name: "Hera Syndulla", email: "hera_syndulla@force.com" },
  { value: "161", name: "Hevy", email: "hevy@force.com" },
  { value: "162", name: "Hondo Ohnaka", email: "hondo_ohnaka@force.com" },
  { value: "163", name: "Huyang", email: "huyang@force.com" },
  { value: "164", name: "Iden Versio", email: "iden_versio@force.com" },
  { value: "165", name: "IG-88", email: "ig-88@force.com" },
  { value: "166", name: "Ima-Gun Di", email: "ima-gun_di@force.com" },
  { value: "167", name: "Inquisitors", email: "inquisitors@force.com" },
  {
    value: "168",
    name: "Inspector Thanoth",
    email: "inspector_thanoth@force.com",
  },
  { value: "169", name: "Jabba", email: "jabba@force.com" },
  { value: "170", name: "Jacen Syndulla", email: "jacen_syndulla@force.com" },
  { value: "171", name: "Jan Dodonna", email: "jan_dodonna@force.com" },
  { value: "172", name: "Jango Fett", email: "jango_fett@force.com" },
  { value: "173", name: "Janus Greejatus", email: "janus_greejatus@force.com" },
  { value: "174", name: "Jar Jar Binks", email: "jar_jar_binks@force.com" },
  { value: "175", name: "Jas Emari", email: "jas_emari@force.com" },
  { value: "176", name: "Jaxxon", email: "jaxxon@force.com" },
  {
    value: "177",
    name: "Jek Tono Porkins",
    email: "jek_tono_porkins@force.com",
  },
  { value: "178", name: "Jeremoch Colton", email: "jeremoch_colton@force.com" },
  { value: "179", name: "Jira", email: "jira@force.com" },
  { value: "180", name: "Jobal Naberrie", email: "jobal_naberrie@force.com" },
  { value: "181", name: "Jocasta Nu", email: "jocasta_nu@force.com" },
  { value: "182", name: "Joclad Danva", email: "joclad_danva@force.com" },
  { value: "183", name: "Joh Yowza", email: "joh_yowza@force.com" },
  { value: "184", name: "Jom Barell", email: "jom_barell@force.com" },
  { value: "185", name: "Joph Seastriker", email: "joph_seastriker@force.com" },
  { value: "186", name: "Jova Tarkin", email: "jova_tarkin@force.com" },
  { value: "187", name: "Jubnuk", email: "jubnuk@force.com" },
  { value: "188", name: "Jyn Erso", email: "jyn_erso@force.com" },
  { value: "189", name: "K-2SO", email: "k-2so@force.com" },
  { value: "190", name: "Kanan Jarrus", email: "kanan_jarrus@force.com" },
  { value: "191", name: "Karbin", email: "karbin@force.com" },
  {
    value: "192",
    name: "Karina the Great",
    email: "karina_the_great@force.com",
  },
  { value: "193", name: "Kes Dameron", email: "kes_dameron@force.com" },
  { value: "194", name: "Ketsu Onyo", email: "ketsu_onyo@force.com" },
  { value: "195", name: "Ki-Adi-Mundi", email: "ki-adi-mundi@force.com" },
  { value: "196", name: "King Katuunko", email: "king_katuunko@force.com" },
  { value: "197", name: "Kit Fisto", email: "kit_fisto@force.com" },
  { value: "198", name: "Kitster Banai", email: "kitster_banai@force.com" },
  { value: "199", name: "Klaatu", email: "klaatu@force.com" },
  { value: "200", name: "Klik-Klak", email: "klik-klak@force.com" },
  { value: "201", name: "Korr Sella", email: "korr_sella@force.com" },
  { value: "202", name: "Kylo Ren", email: "kylo_ren@force.com" },
  { value: "203", name: "L3-37", email: "l3-37@force.com" },
  { value: "204", name: "Lama Su", email: "lama_su@force.com" },
  {
    value: "205",
    name: "Lando Calrissian",
    email: "lando_calrissian@force.com",
  },
  {
    value: "206",
    name: "Lanever Villecham",
    email: "lanever_villecham@force.com",
  },
  { value: "207", name: "Leia Organa", email: "leia_organa@force.com" },
  { value: "208", name: "Letta Turmond", email: "letta_turmond@force.com" },
  {
    value: "209",
    name: "Lieutenant Kaydel Ko Connix",
    email: "lieutenant_kaydel_ko_connix@force.com",
  },
  {
    value: "210",
    name: "Lieutenant Thire",
    email: "lieutenant_thire@force.com",
  },
  { value: "211", name: "Lobot", email: "lobot@force.com" },
  { value: "212", name: "Logray", email: "logray@force.com" },
  { value: "213", name: "Lok Durd", email: "lok_durd@force.com" },
  { value: "214", name: "Longo Two-Guns", email: "longo_two-guns@force.com" },
  { value: "215", name: "Lor San Tekka", email: "lor_san_tekka@force.com" },
  { value: "216", name: "Lorth Needa", email: "lorth_needa@force.com" },
  { value: "217", name: "Lott Dod", email: "lott_dod@force.com" },
  { value: "218", name: "Luke Skywalker", email: "luke_skywalker@force.com" },
  { value: "219", name: "Lumat", email: "lumat@force.com" },
  { value: "220", name: "Luminara Unduli", email: "luminara_unduli@force.com" },
  { value: "221", name: "Lux Bonteri", email: "lux_bonteri@force.com" },
  { value: "222", name: "Lyn Me", email: "lyn_me@force.com" },
  { value: "223", name: "Lyra Erso", email: "lyra_erso@force.com" },
  { value: "224", name: "Mace Windu", email: "mace_windu@force.com" },
  { value: "225", name: "Malakili", email: "malakili@force.com" },
  { value: "226", name: "Mama the Hutt", email: "mama_the_hutt@force.com" },
  { value: "227", name: "Mars Guo", email: "mars_guo@force.com" },
  { value: "228", name: "Mas Amedda", email: "mas_amedda@force.com" },
  { value: "229", name: "Mawhonic", email: "mawhonic@force.com" },
  { value: "230", name: "Max Rebo", email: "max_rebo@force.com" },
  {
    value: "231",
    name: "Maximilian Veers",
    email: "maximilian_veers@force.com",
  },
  { value: "232", name: "Maz Kanata", email: "maz_kanata@force.com" },
  { value: "233", name: "ME-8D9", email: "me-8d9@force.com" },
  { value: "234", name: "Meena Tills", email: "meena_tills@force.com" },
  { value: "235", name: "Mercurial Swift", email: "mercurial_swift@force.com" },
  { value: "236", name: "Mina Bonteri", email: "mina_bonteri@force.com" },
  { value: "237", name: "Miraj Scintel", email: "miraj_scintel@force.com" },
  { value: "238", name: "Mister Bones", email: "mister_bones@force.com" },
  { value: "239", name: "Mod Terrik", email: "mod_terrik@force.com" },
  { value: "240", name: "Moden Canady", email: "moden_canady@force.com" },
  { value: "241", name: "Mon Mothma", email: "mon_mothma@force.com" },
  { value: "242", name: "Moradmin Bast", email: "moradmin_bast@force.com" },
  { value: "243", name: "Moralo Eval", email: "moralo_eval@force.com" },
  { value: "244", name: "Morley", email: "morley@force.com" },
  { value: "245", name: "Mother Talzin", email: "mother_talzin@force.com" },
  { value: "246", name: "Nahdar Vebb", email: "nahdar_vebb@force.com" },
  { value: "247", name: "Nahdonnis Praji", email: "nahdonnis_praji@force.com" },
  { value: "248", name: "Nien Nunb", email: "nien_nunb@force.com" },
  { value: "249", name: "Niima the Hutt", email: "niima_the_hutt@force.com" },
  { value: "250", name: "Nines", email: "nines@force.com" },
  { value: "251", name: "Norra Wexley", email: "norra_wexley@force.com" },
  { value: "252", name: "Nute Gunray", email: "nute_gunray@force.com" },
  { value: "253", name: "Nuvo Vindi", email: "nuvo_vindi@force.com" },
  { value: "254", name: "Obi-Wan Kenobi", email: "obi-wan_kenobi@force.com" },
  { value: "255", name: "Odd Ball", email: "odd_ball@force.com" },
  { value: "256", name: "Ody Mandrell", email: "ody_mandrell@force.com" },
  { value: "257", name: "Omi", email: "omi@force.com" },
  { value: "258", name: "Onaconda Farr", email: "onaconda_farr@force.com" },
  { value: "259", name: "Oola", email: "oola@force.com" },
  { value: "260", name: "OOM-9", email: "oom-9@force.com" },
  { value: "261", name: "Oppo Rancisis", email: "oppo_rancisis@force.com" },
  { value: "262", name: "Orn Free Taa", email: "orn_free_taa@force.com" },
  { value: "263", name: "Oro Dassyne", email: "oro_dassyne@force.com" },
  { value: "264", name: "Orrimarko", email: "orrimarko@force.com" },
  { value: "265", name: "Osi Sobeck", email: "osi_sobeck@force.com" },
  { value: "266", name: "Owen Lars", email: "owen_lars@force.com" },
  { value: "267", name: "Pablo-Jill", email: "pablo-jill@force.com" },
  { value: "268", name: "Padmé Amidala", email: "padmé_amidala@force.com" },
  { value: "269", name: "Pagetti Rook", email: "pagetti_rook@force.com" },
  { value: "270", name: "Paige Tico", email: "paige_tico@force.com" },
  { value: "271", name: "Paploo", email: "paploo@force.com" },
  {
    value: "272",
    name: "Petty Officer Thanisson",
    email: "petty_officer_thanisson@force.com",
  },
  { value: "273", name: "Pharl McQuarrie", email: "pharl_mcquarrie@force.com" },
  { value: "274", name: "Plo Koon", email: "plo_koon@force.com" },
  { value: "275", name: "Po Nudo", email: "po_nudo@force.com" },
  { value: "276", name: "Poe Dameron", email: "poe_dameron@force.com" },
  {
    value: "277",
    name: "Poggle the Lesser",
    email: "poggle_the_lesser@force.com",
  },
  { value: "278", name: "Pong Krell", email: "pong_krell@force.com" },
  { value: "279", name: "Pooja Naberrie", email: "pooja_naberrie@force.com" },
  { value: "280", name: "PZ-4CO", email: "pz-4co@force.com" },
  { value: "281", name: "Quarrie", email: "quarrie@force.com" },
  { value: "282", name: "Quay Tolsite", email: "quay_tolsite@force.com" },
  { value: "283", name: "Queen Apailana", email: "queen_apailana@force.com" },
  { value: "284", name: "Queen Jamillia", email: "queen_jamillia@force.com" },
  { value: "285", name: "Queen Neeyutnee", email: "queen_neeyutnee@force.com" },
  { value: "286", name: "Qui-Gon Jinn", email: "qui-gon_jinn@force.com" },
  { value: "287", name: "Quiggold", email: "quiggold@force.com" },
  { value: "288", name: "Quinlan Vos", email: "quinlan_vos@force.com" },
  { value: "289", name: "R2-D2", email: "r2-d2@force.com" },
  { value: "290", name: "R2-KT", email: "r2-kt@force.com" },
  { value: "291", name: "R3-S6", email: "r3-s6@force.com" },
  { value: "292", name: "R4-P17", email: "r4-p17@force.com" },
  { value: "293", name: "R5-D4", email: "r5-d4@force.com" },
  { value: "294", name: "RA-7", email: "ra-7@force.com" },
  { value: "295", name: "Rabé", email: "rabé@force.com" },
  { value: "296", name: "Rako Hardeen", email: "rako_hardeen@force.com" },
  {
    value: "297",
    name: "Ransolm Casterfo",
    email: "ransolm_casterfo@force.com",
  },
  { value: "298", name: "Rappertunie", email: "rappertunie@force.com" },
  { value: "299", name: "Ratts Tyerell", email: "ratts_tyerell@force.com" },
  { value: "300", name: "Raymus Antilles", email: "raymus_antilles@force.com" },
  { value: "301", name: "Ree-Yees", email: "ree-yees@force.com" },
  { value: "302", name: "Reeve Panzoro", email: "reeve_panzoro@force.com" },
  { value: "303", name: "Rey", email: "rey@force.com" },
  { value: "304", name: "Ric Olié", email: "ric_olié@force.com" },
  { value: "305", name: "Riff Tamson", email: "riff_tamson@force.com" },
  { value: "306", name: "Riley", email: "riley@force.com" },
  { value: "307", name: "Rinnriyin Di", email: "rinnriyin_di@force.com" },
  { value: "308", name: "Rio Durant", email: "rio_durant@force.com" },
  { value: "309", name: "Rogue Squadron", email: "rogue_squadron@force.com" },
  { value: "310", name: "Romba", email: "romba@force.com" },
  { value: "311", name: "Roos Tarpals", email: "roos_tarpals@force.com" },
  { value: "312", name: "Rose Tico", email: "rose_tico@force.com" },
  { value: "313", name: "Rotta the Hutt", email: "rotta_the_hutt@force.com" },
  { value: "314", name: "Rukh", email: "rukh@force.com" },
  { value: "315", name: "Rune Haako", email: "rune_haako@force.com" },
  { value: "316", name: "Rush Clovis", email: "rush_clovis@force.com" },
  { value: "317", name: "Ruwee Naberrie", email: "ruwee_naberrie@force.com" },
  { value: "318", name: "Ryoo Naberrie", email: "ryoo_naberrie@force.com" },
  { value: "319", name: "Sabé", email: "sabé@force.com" },
  { value: "320", name: "Sabine Wren", email: "sabine_wren@force.com" },
  { value: "321", name: "Saché", email: "saché@force.com" },
  { value: "322", name: "Saelt-Marae", email: "saelt-marae@force.com" },
  { value: "323", name: "Saesee Tiin", email: "saesee_tiin@force.com" },
  {
    value: "324",
    name: "Salacious B. Crumb",
    email: "salacious_b._crumb@force.com",
  },
  { value: "325", name: "San Hill", email: "san_hill@force.com" },
  { value: "326", name: "Sana Starros", email: "sana_starros@force.com" },
  { value: "327", name: "Sarco Plank", email: "sarco_plank@force.com" },
  { value: "328", name: "Sarkli", email: "sarkli@force.com" },
  { value: "329", name: "Satine Kryze", email: "satine_kryze@force.com" },
  { value: "330", name: "Savage Opress", email: "savage_opress@force.com" },
  { value: "331", name: "Sebulba", email: "sebulba@force.com" },
  { value: "332", name: "Senator Organa", email: "senator_organa@force.com" },
  { value: "333", name: "Sergeant Kreel", email: "sergeant_kreel@force.com" },
  { value: "334", name: "Seventh Sister", email: "seventh_sister@force.com" },
  { value: "335", name: "Shaak Ti", email: "shaak_ti@force.com" },
  { value: "336", name: "Shara Bey", email: "shara_bey@force.com" },
  { value: "337", name: "Shmi Skywalker", email: "shmi_skywalker@force.com" },
  { value: "338", name: "Shu Mai", email: "shu_mai@force.com" },
  { value: "339", name: "Sidon Ithano", email: "sidon_ithano@force.com" },
  { value: "340", name: "Sifo-Dyas", email: "sifo-dyas@force.com" },
  { value: "341", name: "Sim Aloo", email: "sim_aloo@force.com" },
  {
    value: "342",
    name: "Siniir Rath Velus",
    email: "siniir_rath_velus@force.com",
  },
  { value: "343", name: "Sio Bibble", email: "sio_bibble@force.com" },
  { value: "344", name: "Sixth Brother", email: "sixth_brother@force.com" },
  { value: "345", name: "Slowen Lo", email: "slowen_lo@force.com" },
  { value: "346", name: "Sly Moore", email: "sly_moore@force.com" },
  { value: "347", name: "Snaggletooth", email: "snaggletooth@force.com" },
  { value: "348", name: "Snap Wexley", email: "snap_wexley@force.com" },
  { value: "349", name: "Snoke", email: "snoke@force.com" },
  { value: "350", name: "Sola Naberrie", email: "sola_naberrie@force.com" },
  { value: "351", name: "Sora Bulq", email: "sora_bulq@force.com" },
  { value: "352", name: "Strono Tuggs", email: "strono_tuggs@force.com" },
  { value: "353", name: "Sy Snootles", email: "sy_snootles@force.com" },
  {
    value: "354",
    name: "Tallissan Lintra",
    email: "tallissan_lintra@force.com",
  },
  { value: "355", name: "Tarfful", email: "tarfful@force.com" },
  { value: "356", name: "Tasu Leech", email: "tasu_leech@force.com" },
  { value: "357", name: "Taun We", email: "taun_we@force.com" },
  { value: "358", name: "TC-14", email: "tc-14@force.com" },
  { value: "359", name: "Tee Watt Kaa", email: "tee_watt_kaa@force.com" },
  { value: "360", name: "Teebo", email: "teebo@force.com" },
  { value: "361", name: "Teedo", email: "teedo@force.com" },
  { value: "362", name: "Teemto Pagalies", email: "teemto_pagalies@force.com" },
  { value: "363", name: "Temiri Blagg", email: "temiri_blagg@force.com" },
  { value: "364", name: "Tessek", email: "tessek@force.com" },
  { value: "365", name: "Tey How", email: "tey_how@force.com" },
  { value: "366", name: "Thane Kyrell", email: "thane_kyrell@force.com" },
  { value: "367", name: "The Bendu", email: "the_bendu@force.com" },
  { value: "368", name: "The Smuggler", email: "the_smuggler@force.com" },
  { value: "369", name: "Thrawn", email: "thrawn@force.com" },
  { value: "370", name: "Tiaan Jerjerrod", email: "tiaan_jerjerrod@force.com" },
  { value: "371", name: "Tion Medon", email: "tion_medon@force.com" },
  { value: "372", name: "Tobias Beckett", email: "tobias_beckett@force.com" },
  { value: "373", name: "Tulon Voidgazer", email: "tulon_voidgazer@force.com" },
  { value: "374", name: "Tup", email: "tup@force.com" },
  { value: "375", name: "U9-C4", email: "u9-c4@force.com" },
  { value: "376", name: "Unkar Plutt", email: "unkar_plutt@force.com" },
  { value: "377", name: "Val Beckett", email: "val_beckett@force.com" },
  { value: "378", name: "Vanden Willard", email: "vanden_willard@force.com" },
  {
    value: "379",
    name: "Vice Admiral Amilyn Holdo",
    email: "vice_admiral_amilyn_holdo@force.com",
  },
  { value: "380", name: "Vober Dand", email: "vober_dand@force.com" },
  { value: "381", name: "WAC-47", email: "wac-47@force.com" },
  { value: "382", name: "Wag Too", email: "wag_too@force.com" },
  { value: "383", name: "Wald", email: "wald@force.com" },
  { value: "384", name: "Walrus Man", email: "walrus_man@force.com" },
  { value: "385", name: "Warok", email: "warok@force.com" },
  { value: "386", name: "Wat Tambor", email: "wat_tambor@force.com" },
  { value: "387", name: "Watto", email: "watto@force.com" },
  { value: "388", name: "Wedge Antilles", email: "wedge_antilles@force.com" },
  { value: "389", name: "Wes Janson", email: "wes_janson@force.com" },
  {
    value: "390",
    name: "Wicket W. Warrick",
    email: "wicket_w._warrick@force.com",
  },
  { value: "391", name: "Wilhuff Tarkin", email: "wilhuff_tarkin@force.com" },
  { value: "392", name: "Wollivan", email: "wollivan@force.com" },
  { value: "393", name: "Wuher", email: "wuher@force.com" },
  { value: "394", name: "Wullf Yularen", email: "wullf_yularen@force.com" },
  { value: "395", name: "Xamuel Lennox", email: "xamuel_lennox@force.com" },
  { value: "396", name: "Yaddle", email: "yaddle@force.com" },
  { value: "397", name: "Yarael Poof", email: "yarael_poof@force.com" },
  { value: "398", name: "Yoda", email: "yoda@force.com" },
  { value: "399", name: "Zam Wesell", email: "zam_wesell@force.com" },
  { value: "400", name: "Zev Senesca", email: "zev_senesca@force.com" },
  { value: "401", name: "Ziro the Hutt", email: "ziro_the_hutt@force.com" },
  { value: "402", name: "Zuckuss", email: "zuckuss@force.com" },
];
