import { MentionNodeData } from '../../packages/slate-plugins/src';

export const MENTIONABLES: MentionNodeData[] = [
  { value: 'Aayla Secura' },
  { value: 'Adi Gallia' },
  { value: 'Admiral Dodd Rancit' },
  { value: 'Admiral Firmus Piett' },
  { value: 'Admiral Gial Ackbar' },
  { value: 'Admiral Ozzel' },
  { value: 'Admiral Raddus' },
  { value: 'Admiral Terrinald Screed' },
  { value: 'Admiral Trench' },
  { value: 'Admiral U.O. Statura' },
  { value: 'Agen Kolar' },
  { value: 'Agent Kallus' },
  { value: 'Aiolin and Morit Astarte' },
  { value: 'Aks Moe' },
  { value: 'Almec' },
  { value: 'Alton Kastle' },
  { value: 'Amee' },
  { value: 'AP-5' },
  { value: 'Armitage Hux' },
  { value: 'Artoo' },
  { value: 'Arvel Crynyd' },
  { value: 'Asajj Ventress' },
  { value: 'Aurra Sing' },
  { value: 'AZI-3' },
  { value: 'Bala-Tik' },
  { value: 'Barada' },
  { value: 'Bargwill Tomder' },
  { value: 'Baron Papanoida' },
  { value: 'Barriss Offee' },
  { value: 'Baze Malbus' },
  { value: 'Bazine Netal' },
  { value: 'BB-8' },
  { value: 'BB-9E' },
  { value: 'Ben Quadinaros' },
  { value: 'Berch Teller' },
  { value: 'Beru Lars' },
  { value: 'Bib Fortuna' },
  { value: 'Biggs Darklighter' },
  { value: 'Black Krrsantan' },
  { value: 'Bo-Katan Kryze' },
  { value: 'Boba Fett' },
  { value: 'Bobbajo' },
  { value: 'Bodhi Rook' },
  { value: 'Borvo the Hutt' },
  { value: 'Boss Nass' },
  { value: 'Bossk' },
  { value: 'Breha Antilles-Organa' },
  { value: 'Bren Derlin' },
  { value: 'Brendol Hux' },
  { value: 'BT-1' },
  { value: 'C-3PO' },
  { value: 'C1-10P' },
  { value: 'Cad Bane' },
  { value: 'Caluan Ematt' },
  { value: 'Captain Gregor' },
  { value: 'Captain Phasma' },
  { value: 'Captain Quarsh Panaka' },
  { value: 'Captain Rex' },
  { value: 'Carlist Rieekan' },
  { value: 'Casca Panzoro' },
  { value: 'Cassian Andor' },
  { value: 'Cassio Tagge' },
  { value: 'Cham Syndulla' },
  { value: 'Che Amanwe Papanoida' },
  { value: 'Chewbacca' },
  { value: 'Chi Eekway Papanoida' },
  { value: 'Chief Chirpa' },
  { value: 'Chirrut Îmwe' },
  { value: 'Ciena Ree' },
  { value: 'Cin Drallig' },
  { value: 'Clegg Holdfast' },
  { value: 'Cliegg Lars' },
  { value: 'Coleman Kcaj' },
  { value: 'Coleman Trebor' },
  { value: 'Colonel Kaplan' },
  { value: 'Commander Bly' },
  { value: 'Commander Cody (CC-2224)' },
  { value: 'Commander Fil (CC-3714)' },
  { value: 'Commander Fox' },
  { value: 'Commander Gree' },
  { value: 'Commander Jet' },
  { value: 'Commander Wolffe' },
  { value: 'Conan Antonio Motti' },
  { value: 'Conder Kyl' },
  { value: 'Constable Zuvio' },
  { value: 'Cordé' },
  { value: 'Cpatain Typho' },
  { value: 'Crix Madine' },
  { value: 'Cut Lawquane' },
  { value: 'Dak Ralter' },
  { value: 'Dapp' },
  { value: 'Darth Bane' },
  { value: 'Darth Maul' },
  { value: 'Darth Tyranus' },
  { value: 'Daultay Dofine' },
  { value: 'Del Meeko' },
  { value: 'Delian Mors' },
  { value: 'Dengar' },
  { value: 'Depa Billaba' },
  { value: 'Derek Klivian' },
  { value: 'Dexter Jettster' },
  { value: 'Dineé Ellberger' },
  { value: 'DJ' },
  { value: 'Doctor Aphra' },
  { value: 'Doctor Evazan' },
  { value: 'Dogma' },
  { value: 'Dormé' },
  { value: 'Dr. Cylo' },
  { value: 'Droidbait' },
  { value: 'Droopy McCool' },
  { value: 'Dryden Vos' },
  { value: 'Dud Bolt' },
  { value: 'Ebe E. Endocott' },
  { value: 'Echuu Shen-Jon' },
  { value: 'Eeth Koth' },
  { value: 'Eighth Brother' },
  { value: 'Eirtaé' },
  { value: 'Eli Vanto' },
  { value: 'Ellé' },
  { value: 'Ello Asty' },
  { value: 'Embo' },
  { value: 'Eneb Ray' },
  { value: 'Enfys Nest' },
  { value: 'EV-9D9' },
  { value: 'Evaan Verlaine' },
  { value: 'Even Piell' },
  { value: 'Ezra Bridger' },
  { value: 'Faro Argyus' },
  { value: 'Feral' },
  { value: 'Fifth Brother' },
  { value: 'Finis Valorum' },
  { value: 'Finn' },
  { value: 'Fives' },
  { value: 'FN-1824' },
  { value: 'FN-2003' },
  { value: 'Fodesinbeed Annodue' },
  { value: 'Fulcrum' },
  { value: 'FX-7' },
  { value: 'GA-97' },
  { value: 'Galen Erso' },
  { value: 'Gallius Rax' },
  { value: 'Garazeb "Zeb" Orrelios' },
  { value: 'Gardulla the Hutt' },
  { value: 'Garrick Versio' },
  { value: 'Garven Dreis' },
  { value: 'Gavyn Sykes' },
  { value: 'Gideon Hask' },
  { value: 'Gizor Dellso' },
  { value: 'Gonk droid' },
  { value: 'Grand Inquisitor' },
  { value: 'Greeata Jendowanian' },
  { value: 'Greedo' },
  { value: 'Greer Sonnel' },
  { value: 'Grievous' },
  { value: 'Grummgar' },
  { value: 'Gungi' },
  { value: 'Hammerhead' },
  { value: 'Han Solo' },
  { value: 'Harter Kalonia' },
  { value: 'Has Obbit' },
  { value: 'Hera Syndulla' },
  { value: 'Hevy' },
  { value: 'Hondo Ohnaka' },
  { value: 'Huyang' },
  { value: 'Iden Versio' },
  { value: 'IG-88' },
  { value: 'Ima-Gun Di' },
  { value: 'Inquisitors' },
  { value: 'Inspector Thanoth' },
  { value: 'Jabba' },
  { value: 'Jacen Syndulla' },
  { value: 'Jan Dodonna' },
  { value: 'Jango Fett' },
  { value: 'Janus Greejatus' },
  { value: 'Jar Jar Binks' },
  { value: 'Jas Emari' },
  { value: 'Jaxxon' },
  { value: 'Jek Tono Porkins' },
  { value: 'Jeremoch Colton' },
  { value: 'Jira' },
  { value: 'Jobal Naberrie' },
  { value: 'Jocasta Nu' },
  { value: 'Joclad Danva' },
  { value: 'Joh Yowza' },
  { value: 'Jom Barell' },
  { value: 'Joph Seastriker' },
  { value: 'Jova Tarkin' },
  { value: 'Jubnuk' },
  { value: 'Jyn Erso' },
  { value: 'K-2SO' },
  { value: 'Kanan Jarrus' },
  { value: 'Karbin' },
  { value: 'Karina the Great' },
  { value: 'Kes Dameron' },
  { value: 'Ketsu Onyo' },
  { value: 'Ki-Adi-Mundi' },
  { value: 'King Katuunko' },
  { value: 'Kit Fisto' },
  { value: 'Kitster Banai' },
  { value: 'Klaatu' },
  { value: 'Klik-Klak' },
  { value: 'Korr Sella' },
  { value: 'Kylo Ren' },
  { value: 'L3-37' },
  { value: 'Lama Su' },
  { value: 'Lando Calrissian' },
  { value: 'Lanever Villecham' },
  { value: 'Leia Organa' },
  { value: 'Letta Turmond' },
  { value: 'Lieutenant Kaydel Ko Connix' },
  { value: 'Lieutenant Thire' },
  { value: 'Lobot' },
  { value: 'Logray' },
  { value: 'Lok Durd' },
  { value: 'Longo Two-Guns' },
  { value: 'Lor San Tekka' },
  { value: 'Lorth Needa' },
  { value: 'Lott Dod' },
  { value: 'Luke Skywalker' },
  { value: 'Lumat' },
  { value: 'Luminara Unduli' },
  { value: 'Lux Bonteri' },
  { value: 'Lyn Me' },
  { value: 'Lyra Erso' },
  { value: 'Mace Windu' },
  { value: 'Malakili' },
  { value: 'Mama the Hutt' },
  { value: 'Mars Guo' },
  { value: 'Mas Amedda' },
  { value: 'Mawhonic' },
  { value: 'Max Rebo' },
  { value: 'Maximilian Veers' },
  { value: 'Maz Kanata' },
  { value: 'ME-8D9' },
  { value: 'Meena Tills' },
  { value: 'Mercurial Swift' },
  { value: 'Mina Bonteri' },
  { value: 'Miraj Scintel' },
  { value: 'Mister Bones' },
  { value: 'Mod Terrik' },
  { value: 'Moden Canady' },
  { value: 'Mon Mothma' },
  { value: 'Moradmin Bast' },
  { value: 'Moralo Eval' },
  { value: 'Morley' },
  { value: 'Mother Talzin' },
  { value: 'Nahdar Vebb' },
  { value: 'Nahdonnis Praji' },
  { value: 'Nien Nunb' },
  { value: 'Niima the Hutt' },
  { value: 'Nines' },
  { value: 'Norra Wexley' },
  { value: 'Nute Gunray' },
  { value: 'Nuvo Vindi' },
  { value: 'Obi-Wan Kenobi' },
  { value: 'Odd Ball' },
  { value: 'Ody Mandrell' },
  { value: 'Omi' },
  { value: 'Onaconda Farr' },
  { value: 'Oola' },
  { value: 'OOM-9' },
  { value: 'Oppo Rancisis' },
  { value: 'Orn Free Taa' },
  { value: 'Oro Dassyne' },
  { value: 'Orrimarko' },
  { value: 'Osi Sobeck' },
  { value: 'Owen Lars' },
  { value: 'Pablo-Jill' },
  { value: 'Padmé Amidala' },
  { value: 'Pagetti Rook' },
  { value: 'Paige Tico' },
  { value: 'Paploo' },
  { value: 'Petty Officer Thanisson' },
  { value: 'Pharl McQuarrie' },
  { value: 'Plo Koon' },
  { value: 'Po Nudo' },
  { value: 'Poe Dameron' },
  { value: 'Poggle the Lesser' },
  { value: 'Pong Krell' },
  { value: 'Pooja Naberrie' },
  { value: 'PZ-4CO' },
  { value: 'Quarrie' },
  { value: 'Quay Tolsite' },
  { value: 'Queen Apailana' },
  { value: 'Queen Jamillia' },
  { value: 'Queen Neeyutnee' },
  { value: 'Qui-Gon Jinn' },
  { value: 'Quiggold' },
  { value: 'Quinlan Vos' },
  { value: 'R2-D2' },
  { value: 'R2-KT' },
  { value: 'R3-S6' },
  { value: 'R4-P17' },
  { value: 'R5-D4' },
  { value: 'RA-7' },
  { value: 'Rabé' },
  { value: 'Rako Hardeen' },
  { value: 'Ransolm Casterfo' },
  { value: 'Rappertunie' },
  { value: 'Ratts Tyerell' },
  { value: 'Raymus Antilles' },
  { value: 'Ree-Yees' },
  { value: 'Reeve Panzoro' },
  { value: 'Rey' },
  { value: 'Ric Olié' },
  { value: 'Riff Tamson' },
  { value: 'Riley' },
  { value: 'Rinnriyin Di' },
  { value: 'Rio Durant' },
  { value: 'Rogue Squadron' },
  { value: 'Romba' },
  { value: 'Roos Tarpals' },
  { value: 'Rose Tico' },
  { value: 'Rotta the Hutt' },
  { value: 'Rukh' },
  { value: 'Rune Haako' },
  { value: 'Rush Clovis' },
  { value: 'Ruwee Naberrie' },
  { value: 'Ryoo Naberrie' },
  { value: 'Sabé' },
  { value: 'Sabine Wren' },
  { value: 'Saché' },
  { value: 'Saelt-Marae' },
  { value: 'Saesee Tiin' },
  { value: 'Salacious B. Crumb' },
  { value: 'San Hill' },
  { value: 'Sana Starros' },
  { value: 'Sarco Plank' },
  { value: 'Sarkli' },
  { value: 'Satine Kryze' },
  { value: 'Savage Opress' },
  { value: 'Sebulba' },
  { value: 'Senator Organa' },
  { value: 'Sergeant Kreel' },
  { value: 'Seventh Sister' },
  { value: 'Shaak Ti' },
  { value: 'Shara Bey' },
  { value: 'Shmi Skywalker' },
  { value: 'Shu Mai' },
  { value: 'Sidon Ithano' },
  { value: 'Sifo-Dyas' },
  { value: 'Sim Aloo' },
  { value: 'Siniir Rath Velus' },
  { value: 'Sio Bibble' },
  { value: 'Sixth Brother' },
  { value: 'Slowen Lo' },
  { value: 'Sly Moore' },
  { value: 'Snaggletooth' },
  { value: 'Snap Wexley' },
  { value: 'Snoke' },
  { value: 'Sola Naberrie' },
  { value: 'Sora Bulq' },
  { value: 'Strono Tuggs' },
  { value: 'Sy Snootles' },
  { value: 'Tallissan Lintra' },
  { value: 'Tarfful' },
  { value: 'Tasu Leech' },
  { value: 'Taun We' },
  { value: 'TC-14' },
  { value: 'Tee Watt Kaa' },
  { value: 'Teebo' },
  { value: 'Teedo' },
  { value: 'Teemto Pagalies' },
  { value: 'Temiri Blagg' },
  { value: 'Tessek' },
  { value: 'Tey How' },
  { value: 'Thane Kyrell' },
  { value: 'The Bendu' },
  { value: 'The Smuggler' },
  { value: 'Thrawn' },
  { value: 'Tiaan Jerjerrod' },
  { value: 'Tion Medon' },
  { value: 'Tobias Beckett' },
  { value: 'Tulon Voidgazer' },
  { value: 'Tup' },
  { value: 'U9-C4' },
  { value: 'Unkar Plutt' },
  { value: 'Val Beckett' },
  { value: 'Vanden Willard' },
  { value: 'Vice Admiral Amilyn Holdo' },
  { value: 'Vober Dand' },
  { value: 'WAC-47' },
  { value: 'Wag Too' },
  { value: 'Wald' },
  { value: 'Walrus Man' },
  { value: 'Warok' },
  { value: 'Wat Tambor' },
  { value: 'Watto' },
  { value: 'Wedge Antilles' },
  { value: 'Wes Janson' },
  { value: 'Wicket W. Warrick' },
  { value: 'Wilhuff Tarkin' },
  { value: 'Wollivan' },
  { value: 'Wuher' },
  { value: 'Wullf Yularen' },
  { value: 'Xamuel Lennox' },
  { value: 'Yaddle' },
  { value: 'Yarael Poof' },
  { value: 'Yoda' },
  { value: 'Zam Wesell' },
  { value: 'Zev Senesca' },
  { value: 'Ziro the Hutt' },
  { value: 'Zuckuss' },
];
