export const indexCode = `/**
 * @file Automatically generated by barrelsby.
 */

export * from './CursorOverlayContainer';
export * from './cursorOverlayValue';
export * from './cursorStore';
export * from './dragOverCursorPlugin';
`;

export const indexFile = {
  '/cursor-overlay/index.ts': indexCode,
};
