name: Sandpack

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/package.json'
      - 'examples/src'
      - '.github/workflows/sandpack.yml'

jobs:
  release:
    name: Update Sandpack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # To run comparison we need more than the latest commit. Keep the fetch-depth relatively
          # high or set it to zero to get all commits from the git repo.
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 150
 
      - name: Install
        run: yarn add -D plop@3.1.1
 
      - name: Update Code in Sandpack
        run: yarn gen:code
        
      - name: Update Version in Sandpack
        run: yarn gen:v

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Version Sandpack'
          body: |
            Update Sandpack dependencies. Check the preview before merging.
          commit-message: docs
          committer: GitHub <noreply@github.com>
          branch: docs/sandpack
          delete-branch: true
