export {
  authored,
  isAuthoredEditor,
  type AuthoredEditor,
  type AuthoredPlugin,
} from './authored';
export {
  proposeAuthoredComparison,
  type AuthoredComparisonImportResult,
} from './comparison';
export {
  authoredProjectionDiagnostics,
  createAuthoredImportedRevisionChange,
  createAuthoredReviewDocument,
  parseAuthoredDocument,
  projectAuthoredDocument,
  projectAuthoredRange,
  projectAuthoredReview,
  type AuthoredDocumentProjection,
  type AuthoredFormatProjection,
  type AuthoredFormatPropertyChange,
  type AuthoredFormatSegment,
  type AuthoredImportedRevision,
  type AuthoredImportedRevisionSection,
  type AuthoredProjectionDiagnostic,
  type AuthoredReviewProjection,
  type AuthoredUnresolvedChangeCounts,
} from './format';
export type {
  AuthoredChange,
  AuthoredChangePublication,
  AuthoredChangeContent,
  AuthoredChangeDetails,
  AuthoredChangeKind,
  AuthoredChangeLocation,
  AuthoredChangePart,
  AuthoredChangeReview,
  AuthoredDecision,
  AuthoredOptions,
  AuthoredPage,
  AuthoredQuery,
  AuthoredResult,
  AuthoredSelection,
  AuthoredStatus,
  AuthoredView,
} from './types';
